/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ApiV1ChatsPostRequest
 */
export interface ApiV1ChatsPostRequest {
    /**
     *
     * @type {string}
     * @memberof ApiV1ChatsPostRequest
     */
    name?: string;
}
/**
 * Check if a given object implements the ApiV1ChatsPostRequest interface.
 */
export declare function instanceOfApiV1ChatsPostRequest(value: object): boolean;
export declare function ApiV1ChatsPostRequestFromJSON(json: any): ApiV1ChatsPostRequest;
export declare function ApiV1ChatsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatsPostRequest;
export declare function ApiV1ChatsPostRequestToJSON(value?: ApiV1ChatsPostRequest | null): any;
