"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1SubscribeGet200ResponseAllOfEventsInnerToJSON = exports.ApiV1SubscribeGet200ResponseAllOfEventsInnerFromJSONTyped = exports.ApiV1SubscribeGet200ResponseAllOfEventsInnerFromJSON = exports.instanceOfApiV1SubscribeGet200ResponseAllOfEventsInner = void 0;
const runtime_1 = require("../runtime");
const ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfData_1 = require("./ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfData");
/**
 * Check if a given object implements the ApiV1SubscribeGet200ResponseAllOfEventsInner interface.
 */
function instanceOfApiV1SubscribeGet200ResponseAllOfEventsInner(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1SubscribeGet200ResponseAllOfEventsInner = instanceOfApiV1SubscribeGet200ResponseAllOfEventsInner;
function ApiV1SubscribeGet200ResponseAllOfEventsInnerFromJSON(json) {
    return ApiV1SubscribeGet200ResponseAllOfEventsInnerFromJSONTyped(json, false);
}
exports.ApiV1SubscribeGet200ResponseAllOfEventsInnerFromJSON = ApiV1SubscribeGet200ResponseAllOfEventsInnerFromJSON;
function ApiV1SubscribeGet200ResponseAllOfEventsInnerFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'category': !(0, runtime_1.exists)(json, 'category') ? undefined : json['category'],
        'data': !(0, runtime_1.exists)(json, 'data') ? undefined : (0, ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfData_1.ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfDataFromJSON)(json['data']),
        'timestamp': !(0, runtime_1.exists)(json, 'timestamp') ? undefined : json['timestamp'],
    };
}
exports.ApiV1SubscribeGet200ResponseAllOfEventsInnerFromJSONTyped = ApiV1SubscribeGet200ResponseAllOfEventsInnerFromJSONTyped;
function ApiV1SubscribeGet200ResponseAllOfEventsInnerToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'category': value.category,
        'data': (0, ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfData_1.ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfDataToJSON)(value.data),
        'timestamp': value.timestamp,
    };
}
exports.ApiV1SubscribeGet200ResponseAllOfEventsInnerToJSON = ApiV1SubscribeGet200ResponseAllOfEventsInnerToJSON;
