"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1ChatsChatIdMessagesPostRequestToJSON = exports.ApiV1ChatsChatIdMessagesPostRequestFromJSONTyped = exports.ApiV1ChatsChatIdMessagesPostRequestFromJSON = exports.instanceOfApiV1ChatsChatIdMessagesPostRequest = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1ChatsChatIdMessagesPostRequest interface.
 */
function instanceOfApiV1ChatsChatIdMessagesPostRequest(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1ChatsChatIdMessagesPostRequest = instanceOfApiV1ChatsChatIdMessagesPostRequest;
function ApiV1ChatsChatIdMessagesPostRequestFromJSON(json) {
    return ApiV1ChatsChatIdMessagesPostRequestFromJSONTyped(json, false);
}
exports.ApiV1ChatsChatIdMessagesPostRequestFromJSON = ApiV1ChatsChatIdMessagesPostRequestFromJSON;
function ApiV1ChatsChatIdMessagesPostRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'compressAlgorithm': !(0, runtime_1.exists)(json, 'compress_algorithm') ? undefined : json['compress_algorithm'],
        'content': !(0, runtime_1.exists)(json, 'content') ? undefined : json['content'],
        'cryptAlgorithm': !(0, runtime_1.exists)(json, 'crypt_algorithm') ? undefined : json['crypt_algorithm'],
        'mime': !(0, runtime_1.exists)(json, 'mime') ? undefined : json['mime'],
    };
}
exports.ApiV1ChatsChatIdMessagesPostRequestFromJSONTyped = ApiV1ChatsChatIdMessagesPostRequestFromJSONTyped;
function ApiV1ChatsChatIdMessagesPostRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'compress_algorithm': value.compressAlgorithm,
        'content': value.content,
        'crypt_algorithm': value.cryptAlgorithm,
        'mime': value.mime,
    };
}
exports.ApiV1ChatsChatIdMessagesPostRequestToJSON = ApiV1ChatsChatIdMessagesPostRequestToJSON;
