/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { FileMeta } from './FileMeta';
/**
 *
 * @export
 * @interface ApiV1ChatsChatIdFilesPut200Response
 */
export interface ApiV1ChatsChatIdFilesPut200Response {
    /**
     *
     * @type {FileMeta}
     * @memberof ApiV1ChatsChatIdFilesPut200Response
     */
    data?: FileMeta;
    /**
     *
     * @type {string}
     * @memberof ApiV1ChatsChatIdFilesPut200Response
     */
    status?: string;
}
/**
 * Check if a given object implements the ApiV1ChatsChatIdFilesPut200Response interface.
 */
export declare function instanceOfApiV1ChatsChatIdFilesPut200Response(value: object): boolean;
export declare function ApiV1ChatsChatIdFilesPut200ResponseFromJSON(json: any): ApiV1ChatsChatIdFilesPut200Response;
export declare function ApiV1ChatsChatIdFilesPut200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatsChatIdFilesPut200Response;
export declare function ApiV1ChatsChatIdFilesPut200ResponseToJSON(value?: ApiV1ChatsChatIdFilesPut200Response | null): any;
