/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ApiV1OtsPost200ResponseAllOfData } from './ApiV1OtsPost200ResponseAllOfData';
/**
 *
 * @export
 * @interface ApiV1OtsPost200Response
 */
export interface ApiV1OtsPost200Response {
    /**
     *
     * @type {ApiV1OtsPost200ResponseAllOfData}
     * @memberof ApiV1OtsPost200Response
     */
    data?: ApiV1OtsPost200ResponseAllOfData;
    /**
     *
     * @type {string}
     * @memberof ApiV1OtsPost200Response
     */
    status?: string;
}
/**
 * Check if a given object implements the ApiV1OtsPost200Response interface.
 */
export declare function instanceOfApiV1OtsPost200Response(value: object): boolean;
export declare function ApiV1OtsPost200ResponseFromJSON(json: any): ApiV1OtsPost200Response;
export declare function ApiV1OtsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1OtsPost200Response;
export declare function ApiV1OtsPost200ResponseToJSON(value?: ApiV1OtsPost200Response | null): any;
