/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ApiV1RegisterPostRequestAllOf
 */
export interface ApiV1RegisterPostRequestAllOf {
    /**
     *
     * @type {string}
     * @memberof ApiV1RegisterPostRequestAllOf
     */
    login?: string;
    /**
     *
     * @type {string}
     * @memberof ApiV1RegisterPostRequestAllOf
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof ApiV1RegisterPostRequestAllOf
     */
    password?: string;
}
/**
 * Check if a given object implements the ApiV1RegisterPostRequestAllOf interface.
 */
export declare function instanceOfApiV1RegisterPostRequestAllOf(value: object): boolean;
export declare function ApiV1RegisterPostRequestAllOfFromJSON(json: any): ApiV1RegisterPostRequestAllOf;
export declare function ApiV1RegisterPostRequestAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RegisterPostRequestAllOf;
export declare function ApiV1RegisterPostRequestAllOfToJSON(value?: ApiV1RegisterPostRequestAllOf | null): any;
