/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ApiV1ChatsChatIdInvitePost200Response
 */
export interface ApiV1ChatsChatIdInvitePost200Response {
    /**
     *
     * @type {object}
     * @memberof ApiV1ChatsChatIdInvitePost200Response
     */
    fiberMap?: object;
    /**
     *
     * @type {string}
     * @memberof ApiV1ChatsChatIdInvitePost200Response
     */
    status?: string;
}
/**
 * Check if a given object implements the ApiV1ChatsChatIdInvitePost200Response interface.
 */
export declare function instanceOfApiV1ChatsChatIdInvitePost200Response(value: object): boolean;
export declare function ApiV1ChatsChatIdInvitePost200ResponseFromJSON(json: any): ApiV1ChatsChatIdInvitePost200Response;
export declare function ApiV1ChatsChatIdInvitePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatsChatIdInvitePost200Response;
export declare function ApiV1ChatsChatIdInvitePost200ResponseToJSON(value?: ApiV1ChatsChatIdInvitePost200Response | null): any;
