"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1LoginPost200ResponseDataAllOfToJSON = exports.ApiV1LoginPost200ResponseDataAllOfFromJSONTyped = exports.ApiV1LoginPost200ResponseDataAllOfFromJSON = exports.instanceOfApiV1LoginPost200ResponseDataAllOf = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1LoginPost200ResponseDataAllOf interface.
 */
function instanceOfApiV1LoginPost200ResponseDataAllOf(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1LoginPost200ResponseDataAllOf = instanceOfApiV1LoginPost200ResponseDataAllOf;
function ApiV1LoginPost200ResponseDataAllOfFromJSON(json) {
    return ApiV1LoginPost200ResponseDataAllOfFromJSONTyped(json, false);
}
exports.ApiV1LoginPost200ResponseDataAllOfFromJSON = ApiV1LoginPost200ResponseDataAllOfFromJSON;
function ApiV1LoginPost200ResponseDataAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'token': !(0, runtime_1.exists)(json, 'token') ? undefined : json['token'],
    };
}
exports.ApiV1LoginPost200ResponseDataAllOfFromJSONTyped = ApiV1LoginPost200ResponseDataAllOfFromJSONTyped;
function ApiV1LoginPost200ResponseDataAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'token': value.token,
    };
}
exports.ApiV1LoginPost200ResponseDataAllOfToJSON = ApiV1LoginPost200ResponseDataAllOfToJSON;
