/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ApiV1ChatsChatIdMessagesMessageIdPatchRequest
 */
export interface ApiV1ChatsChatIdMessagesMessageIdPatchRequest {
    /**
     *
     * @type {string}
     * @memberof ApiV1ChatsChatIdMessagesMessageIdPatchRequest
     */
    clientSideId?: string;
    /**
     *
     * @type {string}
     * @memberof ApiV1ChatsChatIdMessagesMessageIdPatchRequest
     */
    compressAlgorithm?: string;
    /**
     *
     * @type {string}
     * @memberof ApiV1ChatsChatIdMessagesMessageIdPatchRequest
     */
    content?: string;
    /**
     *
     * @type {string}
     * @memberof ApiV1ChatsChatIdMessagesMessageIdPatchRequest
     */
    cryptAlgorithm?: string;
}
/**
 * Check if a given object implements the ApiV1ChatsChatIdMessagesMessageIdPatchRequest interface.
 */
export declare function instanceOfApiV1ChatsChatIdMessagesMessageIdPatchRequest(value: object): boolean;
export declare function ApiV1ChatsChatIdMessagesMessageIdPatchRequestFromJSON(json: any): ApiV1ChatsChatIdMessagesMessageIdPatchRequest;
export declare function ApiV1ChatsChatIdMessagesMessageIdPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatsChatIdMessagesMessageIdPatchRequest;
export declare function ApiV1ChatsChatIdMessagesMessageIdPatchRequestToJSON(value?: ApiV1ChatsChatIdMessagesMessageIdPatchRequest | null): any;
