"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1LoginPost200ResponseAllOfDataToJSON = exports.ApiV1LoginPost200ResponseAllOfDataFromJSONTyped = exports.ApiV1LoginPost200ResponseAllOfDataFromJSON = exports.instanceOfApiV1LoginPost200ResponseAllOfData = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1LoginPost200ResponseAllOfData interface.
 */
function instanceOfApiV1LoginPost200ResponseAllOfData(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1LoginPost200ResponseAllOfData = instanceOfApiV1LoginPost200ResponseAllOfData;
function ApiV1LoginPost200ResponseAllOfDataFromJSON(json) {
    return ApiV1LoginPost200ResponseAllOfDataFromJSONTyped(json, false);
}
exports.ApiV1LoginPost200ResponseAllOfDataFromJSON = ApiV1LoginPost200ResponseAllOfDataFromJSON;
function ApiV1LoginPost200ResponseAllOfDataFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'token': !(0, runtime_1.exists)(json, 'token') ? undefined : json['token'],
    };
}
exports.ApiV1LoginPost200ResponseAllOfDataFromJSONTyped = ApiV1LoginPost200ResponseAllOfDataFromJSONTyped;
function ApiV1LoginPost200ResponseAllOfDataToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'token': value.token,
    };
}
exports.ApiV1LoginPost200ResponseAllOfDataToJSON = ApiV1LoginPost200ResponseAllOfDataToJSON;
