/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { MessageMessage } from './MessageMessage';
/**
 *
 * @export
 * @interface ApiV1ChatsChatIdMessagesGet200Response
 */
export interface ApiV1ChatsChatIdMessagesGet200Response {
    /**
     *
     * @type {Array<MessageMessage>}
     * @memberof ApiV1ChatsChatIdMessagesGet200Response
     */
    data?: Array<MessageMessage>;
    /**
     *
     * @type {object}
     * @memberof ApiV1ChatsChatIdMessagesGet200Response
     */
    fiberMap?: object;
    /**
     *
     * @type {string}
     * @memberof ApiV1ChatsChatIdMessagesGet200Response
     */
    status?: string;
}
/**
 * Check if a given object implements the ApiV1ChatsChatIdMessagesGet200Response interface.
 */
export declare function instanceOfApiV1ChatsChatIdMessagesGet200Response(value: object): boolean;
export declare function ApiV1ChatsChatIdMessagesGet200ResponseFromJSON(json: any): ApiV1ChatsChatIdMessagesGet200Response;
export declare function ApiV1ChatsChatIdMessagesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatsChatIdMessagesGet200Response;
export declare function ApiV1ChatsChatIdMessagesGet200ResponseToJSON(value?: ApiV1ChatsChatIdMessagesGet200Response | null): any;
