/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ChatChat } from './ChatChat';
/**
 *
 * @export
 * @interface ApiV1ChatsGet200Response
 */
export interface ApiV1ChatsGet200Response {
    /**
     *
     * @type {Array<ChatChat>}
     * @memberof ApiV1ChatsGet200Response
     */
    data?: Array<ChatChat>;
    /**
     *
     * @type {string}
     * @memberof ApiV1ChatsGet200Response
     */
    status?: string;
}
/**
 * Check if a given object implements the ApiV1ChatsGet200Response interface.
 */
export declare function instanceOfApiV1ChatsGet200Response(value: object): boolean;
export declare function ApiV1ChatsGet200ResponseFromJSON(json: any): ApiV1ChatsGet200Response;
export declare function ApiV1ChatsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatsGet200Response;
export declare function ApiV1ChatsGet200ResponseToJSON(value?: ApiV1ChatsGet200Response | null): any;
