/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ApiV1SubscribeGet200ResponseEventsInnerAllOfData } from './ApiV1SubscribeGet200ResponseEventsInnerAllOfData';
/**
 *
 * @export
 * @interface ApiV1SubscribeGet200ResponseEventsInner
 */
export interface ApiV1SubscribeGet200ResponseEventsInner {
    /**
     *
     * @type {string}
     * @memberof ApiV1SubscribeGet200ResponseEventsInner
     */
    category?: string;
    /**
     *
     * @type {ApiV1SubscribeGet200ResponseEventsInnerAllOfData}
     * @memberof ApiV1SubscribeGet200ResponseEventsInner
     */
    data?: ApiV1SubscribeGet200ResponseEventsInnerAllOfData;
    /**
     *
     * @type {number}
     * @memberof ApiV1SubscribeGet200ResponseEventsInner
     */
    timestamp?: number;
}
/**
 * Check if a given object implements the ApiV1SubscribeGet200ResponseEventsInner interface.
 */
export declare function instanceOfApiV1SubscribeGet200ResponseEventsInner(value: object): boolean;
export declare function ApiV1SubscribeGet200ResponseEventsInnerFromJSON(json: any): ApiV1SubscribeGet200ResponseEventsInner;
export declare function ApiV1SubscribeGet200ResponseEventsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SubscribeGet200ResponseEventsInner;
export declare function ApiV1SubscribeGet200ResponseEventsInnerToJSON(value?: ApiV1SubscribeGet200ResponseEventsInner | null): any;
