/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ApiV1OtsPost200ResponseAllOfData
 */
export interface ApiV1OtsPost200ResponseAllOfData {
    /**
     *
     * @type {string}
     * @memberof ApiV1OtsPost200ResponseAllOfData
     */
    code?: string;
}
/**
 * Check if a given object implements the ApiV1OtsPost200ResponseAllOfData interface.
 */
export declare function instanceOfApiV1OtsPost200ResponseAllOfData(value: object): boolean;
export declare function ApiV1OtsPost200ResponseAllOfDataFromJSON(json: any): ApiV1OtsPost200ResponseAllOfData;
export declare function ApiV1OtsPost200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1OtsPost200ResponseAllOfData;
export declare function ApiV1OtsPost200ResponseAllOfDataToJSON(value?: ApiV1OtsPost200ResponseAllOfData | null): any;
