/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ApiV1LoginPost200ResponseAllOfData
 */
export interface ApiV1LoginPost200ResponseAllOfData {
    /**
     *
     * @type {string}
     * @memberof ApiV1LoginPost200ResponseAllOfData
     */
    token?: string;
}
/**
 * Check if a given object implements the ApiV1LoginPost200ResponseAllOfData interface.
 */
export declare function instanceOfApiV1LoginPost200ResponseAllOfData(value: object): boolean;
export declare function ApiV1LoginPost200ResponseAllOfDataFromJSON(json: any): ApiV1LoginPost200ResponseAllOfData;
export declare function ApiV1LoginPost200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1LoginPost200ResponseAllOfData;
export declare function ApiV1LoginPost200ResponseAllOfDataToJSON(value?: ApiV1LoginPost200ResponseAllOfData | null): any;
