"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1ChatsChatIdInvitePostRequestToJSON = exports.ApiV1ChatsChatIdInvitePostRequestFromJSONTyped = exports.ApiV1ChatsChatIdInvitePostRequestFromJSON = exports.instanceOfApiV1ChatsChatIdInvitePostRequest = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1ChatsChatIdInvitePostRequest interface.
 */
function instanceOfApiV1ChatsChatIdInvitePostRequest(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1ChatsChatIdInvitePostRequest = instanceOfApiV1ChatsChatIdInvitePostRequest;
function ApiV1ChatsChatIdInvitePostRequestFromJSON(json) {
    return ApiV1ChatsChatIdInvitePostRequestFromJSONTyped(json, false);
}
exports.ApiV1ChatsChatIdInvitePostRequestFromJSON = ApiV1ChatsChatIdInvitePostRequestFromJSON;
function ApiV1ChatsChatIdInvitePostRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'login': !(0, runtime_1.exists)(json, 'login') ? undefined : json['login'],
    };
}
exports.ApiV1ChatsChatIdInvitePostRequestFromJSONTyped = ApiV1ChatsChatIdInvitePostRequestFromJSONTyped;
function ApiV1ChatsChatIdInvitePostRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'login': value.login,
    };
}
exports.ApiV1ChatsChatIdInvitePostRequestToJSON = ApiV1ChatsChatIdInvitePostRequestToJSON;
