/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ApiV1SubscribeGet200ResponseEventsInnerAllOfData } from './ApiV1SubscribeGet200ResponseEventsInnerAllOfData';
/**
 *
 * @export
 * @interface ApiV1SubscribeGet200ResponseEventsInnerAllOf
 */
export interface ApiV1SubscribeGet200ResponseEventsInnerAllOf {
    /**
     *
     * @type {string}
     * @memberof ApiV1SubscribeGet200ResponseEventsInnerAllOf
     */
    category?: string;
    /**
     *
     * @type {ApiV1SubscribeGet200ResponseEventsInnerAllOfData}
     * @memberof ApiV1SubscribeGet200ResponseEventsInnerAllOf
     */
    data?: ApiV1SubscribeGet200ResponseEventsInnerAllOfData;
    /**
     *
     * @type {number}
     * @memberof ApiV1SubscribeGet200ResponseEventsInnerAllOf
     */
    timestamp?: number;
}
/**
 * Check if a given object implements the ApiV1SubscribeGet200ResponseEventsInnerAllOf interface.
 */
export declare function instanceOfApiV1SubscribeGet200ResponseEventsInnerAllOf(value: object): boolean;
export declare function ApiV1SubscribeGet200ResponseEventsInnerAllOfFromJSON(json: any): ApiV1SubscribeGet200ResponseEventsInnerAllOf;
export declare function ApiV1SubscribeGet200ResponseEventsInnerAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SubscribeGet200ResponseEventsInnerAllOf;
export declare function ApiV1SubscribeGet200ResponseEventsInnerAllOfToJSON(value?: ApiV1SubscribeGet200ResponseEventsInnerAllOf | null): any;
