/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ApiV1RegisterPostRequest
 */
export interface ApiV1RegisterPostRequest {
    /**
     *
     * @type {string}
     * @memberof ApiV1RegisterPostRequest
     */
    login?: string;
    /**
     *
     * @type {string}
     * @memberof ApiV1RegisterPostRequest
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof ApiV1RegisterPostRequest
     */
    password?: string;
}
/**
 * Check if a given object implements the ApiV1RegisterPostRequest interface.
 */
export declare function instanceOfApiV1RegisterPostRequest(value: object): boolean;
export declare function ApiV1RegisterPostRequestFromJSON(json: any): ApiV1RegisterPostRequest;
export declare function ApiV1RegisterPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RegisterPostRequest;
export declare function ApiV1RegisterPostRequestToJSON(value?: ApiV1RegisterPostRequest | null): any;
