/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ApiV1PushWebServerPublicKeyGet200Response
 */
export interface ApiV1PushWebServerPublicKeyGet200Response {
    /**
     *
     * @type {string}
     * @memberof ApiV1PushWebServerPublicKeyGet200Response
     */
    data?: string;
    /**
     *
     * @type {object}
     * @memberof ApiV1PushWebServerPublicKeyGet200Response
     */
    fiberMap?: object;
    /**
     *
     * @type {string}
     * @memberof ApiV1PushWebServerPublicKeyGet200Response
     */
    status?: string;
}
/**
 * Check if a given object implements the ApiV1PushWebServerPublicKeyGet200Response interface.
 */
export declare function instanceOfApiV1PushWebServerPublicKeyGet200Response(value: object): boolean;
export declare function ApiV1PushWebServerPublicKeyGet200ResponseFromJSON(json: any): ApiV1PushWebServerPublicKeyGet200Response;
export declare function ApiV1PushWebServerPublicKeyGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1PushWebServerPublicKeyGet200Response;
export declare function ApiV1PushWebServerPublicKeyGet200ResponseToJSON(value?: ApiV1PushWebServerPublicKeyGet200Response | null): any;
