"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1PushWebSubscribePostRequestToJSON = exports.ApiV1PushWebSubscribePostRequestFromJSONTyped = exports.ApiV1PushWebSubscribePostRequestFromJSON = exports.instanceOfApiV1PushWebSubscribePostRequest = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1PushWebSubscribePostRequest interface.
 */
function instanceOfApiV1PushWebSubscribePostRequest(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1PushWebSubscribePostRequest = instanceOfApiV1PushWebSubscribePostRequest;
function ApiV1PushWebSubscribePostRequestFromJSON(json) {
    return ApiV1PushWebSubscribePostRequestFromJSONTyped(json, false);
}
exports.ApiV1PushWebSubscribePostRequestFromJSON = ApiV1PushWebSubscribePostRequestFromJSON;
function ApiV1PushWebSubscribePostRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'token': !(0, runtime_1.exists)(json, 'token') ? undefined : json['token'],
    };
}
exports.ApiV1PushWebSubscribePostRequestFromJSONTyped = ApiV1PushWebSubscribePostRequestFromJSONTyped;
function ApiV1PushWebSubscribePostRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'token': value.token,
    };
}
exports.ApiV1PushWebSubscribePostRequestToJSON = ApiV1PushWebSubscribePostRequestToJSON;
