"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1RegisterPostRequestAllOfToJSON = exports.ApiV1RegisterPostRequestAllOfFromJSONTyped = exports.ApiV1RegisterPostRequestAllOfFromJSON = exports.instanceOfApiV1RegisterPostRequestAllOf = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1RegisterPostRequestAllOf interface.
 */
function instanceOfApiV1RegisterPostRequestAllOf(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1RegisterPostRequestAllOf = instanceOfApiV1RegisterPostRequestAllOf;
function ApiV1RegisterPostRequestAllOfFromJSON(json) {
    return ApiV1RegisterPostRequestAllOfFromJSONTyped(json, false);
}
exports.ApiV1RegisterPostRequestAllOfFromJSON = ApiV1RegisterPostRequestAllOfFromJSON;
function ApiV1RegisterPostRequestAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'login': !(0, runtime_1.exists)(json, 'login') ? undefined : json['login'],
        'name': !(0, runtime_1.exists)(json, 'name') ? undefined : json['name'],
        'password': !(0, runtime_1.exists)(json, 'password') ? undefined : json['password'],
    };
}
exports.ApiV1RegisterPostRequestAllOfFromJSONTyped = ApiV1RegisterPostRequestAllOfFromJSONTyped;
function ApiV1RegisterPostRequestAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'login': value.login,
        'name': value.name,
        'password': value.password,
    };
}
exports.ApiV1RegisterPostRequestAllOfToJSON = ApiV1RegisterPostRequestAllOfToJSON;
