"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1SubscribeGet200ResponseToJSON = exports.ApiV1SubscribeGet200ResponseFromJSONTyped = exports.ApiV1SubscribeGet200ResponseFromJSON = exports.instanceOfApiV1SubscribeGet200Response = void 0;
const runtime_1 = require("../runtime");
const ApiV1SubscribeGet200ResponseEventsInner_1 = require("./ApiV1SubscribeGet200ResponseEventsInner");
/**
 * Check if a given object implements the ApiV1SubscribeGet200Response interface.
 */
function instanceOfApiV1SubscribeGet200Response(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1SubscribeGet200Response = instanceOfApiV1SubscribeGet200Response;
function ApiV1SubscribeGet200ResponseFromJSON(json) {
    return ApiV1SubscribeGet200ResponseFromJSONTyped(json, false);
}
exports.ApiV1SubscribeGet200ResponseFromJSON = ApiV1SubscribeGet200ResponseFromJSON;
function ApiV1SubscribeGet200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'events': !(0, runtime_1.exists)(json, 'events') ? undefined : (json['events'].map(ApiV1SubscribeGet200ResponseEventsInner_1.ApiV1SubscribeGet200ResponseEventsInnerFromJSON)),
        'fiberMap': !(0, runtime_1.exists)(json, 'fiber.Map') ? undefined : json['fiber.Map'],
    };
}
exports.ApiV1SubscribeGet200ResponseFromJSONTyped = ApiV1SubscribeGet200ResponseFromJSONTyped;
function ApiV1SubscribeGet200ResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'events': value.events === undefined ? undefined : (value.events.map(ApiV1SubscribeGet200ResponseEventsInner_1.ApiV1SubscribeGet200ResponseEventsInnerToJSON)),
        'fiber.Map': value.fiberMap,
    };
}
exports.ApiV1SubscribeGet200ResponseToJSON = ApiV1SubscribeGet200ResponseToJSON;
