"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1ChatsGet200ResponseToJSON = exports.ApiV1ChatsGet200ResponseFromJSONTyped = exports.ApiV1ChatsGet200ResponseFromJSON = exports.instanceOfApiV1ChatsGet200Response = void 0;
const runtime_1 = require("../runtime");
const ChatChat_1 = require("./ChatChat");
/**
 * Check if a given object implements the ApiV1ChatsGet200Response interface.
 */
function instanceOfApiV1ChatsGet200Response(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1ChatsGet200Response = instanceOfApiV1ChatsGet200Response;
function ApiV1ChatsGet200ResponseFromJSON(json) {
    return ApiV1ChatsGet200ResponseFromJSONTyped(json, false);
}
exports.ApiV1ChatsGet200ResponseFromJSON = ApiV1ChatsGet200ResponseFromJSON;
function ApiV1ChatsGet200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': !(0, runtime_1.exists)(json, 'data') ? undefined : (json['data'].map(ChatChat_1.ChatChatFromJSON)),
        'status': !(0, runtime_1.exists)(json, 'status') ? undefined : json['status'],
    };
}
exports.ApiV1ChatsGet200ResponseFromJSONTyped = ApiV1ChatsGet200ResponseFromJSONTyped;
function ApiV1ChatsGet200ResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': value.data === undefined ? undefined : (value.data.map(ChatChat_1.ChatChatToJSON)),
        'status': value.status,
    };
}
exports.ApiV1ChatsGet200ResponseToJSON = ApiV1ChatsGet200ResponseToJSON;
