"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1SessionsGet200ResponseToJSON = exports.ApiV1SessionsGet200ResponseFromJSONTyped = exports.ApiV1SessionsGet200ResponseFromJSON = exports.instanceOfApiV1SessionsGet200Response = void 0;
const runtime_1 = require("../runtime");
const AuthSession_1 = require("./AuthSession");
/**
 * Check if a given object implements the ApiV1SessionsGet200Response interface.
 */
function instanceOfApiV1SessionsGet200Response(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1SessionsGet200Response = instanceOfApiV1SessionsGet200Response;
function ApiV1SessionsGet200ResponseFromJSON(json) {
    return ApiV1SessionsGet200ResponseFromJSONTyped(json, false);
}
exports.ApiV1SessionsGet200ResponseFromJSON = ApiV1SessionsGet200ResponseFromJSON;
function ApiV1SessionsGet200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': !(0, runtime_1.exists)(json, 'data') ? undefined : (json['data'].map(AuthSession_1.AuthSessionFromJSON)),
        'status': !(0, runtime_1.exists)(json, 'status') ? undefined : json['status'],
    };
}
exports.ApiV1SessionsGet200ResponseFromJSONTyped = ApiV1SessionsGet200ResponseFromJSONTyped;
function ApiV1SessionsGet200ResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': value.data === undefined ? undefined : (value.data.map(AuthSession_1.AuthSessionToJSON)),
        'status': value.status,
    };
}
exports.ApiV1SessionsGet200ResponseToJSON = ApiV1SessionsGet200ResponseToJSON;
