/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ApiV1LoginPostRequestAllOf
 */
export interface ApiV1LoginPostRequestAllOf {
    /**
     *
     * @type {string}
     * @memberof ApiV1LoginPostRequestAllOf
     */
    login?: string;
    /**
     *
     * @type {string}
     * @memberof ApiV1LoginPostRequestAllOf
     */
    password?: string;
}
/**
 * Check if a given object implements the ApiV1LoginPostRequestAllOf interface.
 */
export declare function instanceOfApiV1LoginPostRequestAllOf(value: object): boolean;
export declare function ApiV1LoginPostRequestAllOfFromJSON(json: any): ApiV1LoginPostRequestAllOf;
export declare function ApiV1LoginPostRequestAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1LoginPostRequestAllOf;
export declare function ApiV1LoginPostRequestAllOfToJSON(value?: ApiV1LoginPostRequestAllOf | null): any;
