"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1ChatsPostRequestToJSON = exports.ApiV1ChatsPostRequestFromJSONTyped = exports.ApiV1ChatsPostRequestFromJSON = exports.instanceOfApiV1ChatsPostRequest = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1ChatsPostRequest interface.
 */
function instanceOfApiV1ChatsPostRequest(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1ChatsPostRequest = instanceOfApiV1ChatsPostRequest;
function ApiV1ChatsPostRequestFromJSON(json) {
    return ApiV1ChatsPostRequestFromJSONTyped(json, false);
}
exports.ApiV1ChatsPostRequestFromJSON = ApiV1ChatsPostRequestFromJSON;
function ApiV1ChatsPostRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'name': !(0, runtime_1.exists)(json, 'name') ? undefined : json['name'],
    };
}
exports.ApiV1ChatsPostRequestFromJSONTyped = ApiV1ChatsPostRequestFromJSONTyped;
function ApiV1ChatsPostRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'name': value.name,
    };
}
exports.ApiV1ChatsPostRequestToJSON = ApiV1ChatsPostRequestToJSON;
