"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1ChatsChatIdInvitePostRequestAllOfToJSON = exports.ApiV1ChatsChatIdInvitePostRequestAllOfFromJSONTyped = exports.ApiV1ChatsChatIdInvitePostRequestAllOfFromJSON = exports.instanceOfApiV1ChatsChatIdInvitePostRequestAllOf = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1ChatsChatIdInvitePostRequestAllOf interface.
 */
function instanceOfApiV1ChatsChatIdInvitePostRequestAllOf(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1ChatsChatIdInvitePostRequestAllOf = instanceOfApiV1ChatsChatIdInvitePostRequestAllOf;
function ApiV1ChatsChatIdInvitePostRequestAllOfFromJSON(json) {
    return ApiV1ChatsChatIdInvitePostRequestAllOfFromJSONTyped(json, false);
}
exports.ApiV1ChatsChatIdInvitePostRequestAllOfFromJSON = ApiV1ChatsChatIdInvitePostRequestAllOfFromJSON;
function ApiV1ChatsChatIdInvitePostRequestAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'login': !(0, runtime_1.exists)(json, 'login') ? undefined : json['login'],
    };
}
exports.ApiV1ChatsChatIdInvitePostRequestAllOfFromJSONTyped = ApiV1ChatsChatIdInvitePostRequestAllOfFromJSONTyped;
function ApiV1ChatsChatIdInvitePostRequestAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'login': value.login,
    };
}
exports.ApiV1ChatsChatIdInvitePostRequestAllOfToJSON = ApiV1ChatsChatIdInvitePostRequestAllOfToJSON;
