"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1OtsPostRequestToJSON = exports.ApiV1OtsPostRequestFromJSONTyped = exports.ApiV1OtsPostRequestFromJSON = exports.instanceOfApiV1OtsPostRequest = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1OtsPostRequest interface.
 */
function instanceOfApiV1OtsPostRequest(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1OtsPostRequest = instanceOfApiV1OtsPostRequest;
function ApiV1OtsPostRequestFromJSON(json) {
    return ApiV1OtsPostRequestFromJSONTyped(json, false);
}
exports.ApiV1OtsPostRequestFromJSON = ApiV1OtsPostRequestFromJSON;
function ApiV1OtsPostRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': !(0, runtime_1.exists)(json, 'data') ? undefined : json['data'],
    };
}
exports.ApiV1OtsPostRequestFromJSONTyped = ApiV1OtsPostRequestFromJSONTyped;
function ApiV1OtsPostRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': value.data,
    };
}
exports.ApiV1OtsPostRequestToJSON = ApiV1OtsPostRequestToJSON;
