/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ApiV1LoginPost200ResponseAllOfData } from './ApiV1LoginPost200ResponseAllOfData';
/**
 *
 * @export
 * @interface ApiV1LoginPost200Response
 */
export interface ApiV1LoginPost200Response {
    /**
     *
     * @type {ApiV1LoginPost200ResponseAllOfData}
     * @memberof ApiV1LoginPost200Response
     */
    data?: ApiV1LoginPost200ResponseAllOfData;
    /**
     *
     * @type {string}
     * @memberof ApiV1LoginPost200Response
     */
    status?: string;
}
/**
 * Check if a given object implements the ApiV1LoginPost200Response interface.
 */
export declare function instanceOfApiV1LoginPost200Response(value: object): boolean;
export declare function ApiV1LoginPost200ResponseFromJSON(json: any): ApiV1LoginPost200Response;
export declare function ApiV1LoginPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1LoginPost200Response;
export declare function ApiV1LoginPost200ResponseToJSON(value?: ApiV1LoginPost200Response | null): any;
