"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfDataToJSON = exports.ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfDataFromJSONTyped = exports.ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfDataFromJSON = exports.instanceOfApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfData = void 0;
const runtime_1 = require("../runtime");
const MessageMessage_1 = require("./MessageMessage");
/**
 * Check if a given object implements the ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfData interface.
 */
function instanceOfApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfData(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfData = instanceOfApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfData;
function ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfDataFromJSON(json) {
    return ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfDataFromJSONTyped(json, false);
}
exports.ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfDataFromJSON = ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfDataFromJSON;
function ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfDataFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'message': !(0, runtime_1.exists)(json, 'message') ? undefined : (0, MessageMessage_1.MessageMessageFromJSON)(json['message']),
    };
}
exports.ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfDataFromJSONTyped = ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfDataFromJSONTyped;
function ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfDataToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'message': (0, MessageMessage_1.MessageMessageToJSON)(value.message),
    };
}
exports.ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfDataToJSON = ApiV1SubscribeGet200ResponseAllOfEventsInnerAllOfDataToJSON;
