"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1ChatsChatIdFilesPut200ResponseToJSON = exports.ApiV1ChatsChatIdFilesPut200ResponseFromJSONTyped = exports.ApiV1ChatsChatIdFilesPut200ResponseFromJSON = exports.instanceOfApiV1ChatsChatIdFilesPut200Response = void 0;
const runtime_1 = require("../runtime");
const FileMeta_1 = require("./FileMeta");
/**
 * Check if a given object implements the ApiV1ChatsChatIdFilesPut200Response interface.
 */
function instanceOfApiV1ChatsChatIdFilesPut200Response(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1ChatsChatIdFilesPut200Response = instanceOfApiV1ChatsChatIdFilesPut200Response;
function ApiV1ChatsChatIdFilesPut200ResponseFromJSON(json) {
    return ApiV1ChatsChatIdFilesPut200ResponseFromJSONTyped(json, false);
}
exports.ApiV1ChatsChatIdFilesPut200ResponseFromJSON = ApiV1ChatsChatIdFilesPut200ResponseFromJSON;
function ApiV1ChatsChatIdFilesPut200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': !(0, runtime_1.exists)(json, 'data') ? undefined : (0, FileMeta_1.FileMetaFromJSON)(json['data']),
        'status': !(0, runtime_1.exists)(json, 'status') ? undefined : json['status'],
    };
}
exports.ApiV1ChatsChatIdFilesPut200ResponseFromJSONTyped = ApiV1ChatsChatIdFilesPut200ResponseFromJSONTyped;
function ApiV1ChatsChatIdFilesPut200ResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': (0, FileMeta_1.FileMetaToJSON)(value.data),
        'status': value.status,
    };
}
exports.ApiV1ChatsChatIdFilesPut200ResponseToJSON = ApiV1ChatsChatIdFilesPut200ResponseToJSON;
