"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1ChatsChatIdMessagesMessageIdPatchRequestToJSON = exports.ApiV1ChatsChatIdMessagesMessageIdPatchRequestFromJSONTyped = exports.ApiV1ChatsChatIdMessagesMessageIdPatchRequestFromJSON = exports.instanceOfApiV1ChatsChatIdMessagesMessageIdPatchRequest = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1ChatsChatIdMessagesMessageIdPatchRequest interface.
 */
function instanceOfApiV1ChatsChatIdMessagesMessageIdPatchRequest(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1ChatsChatIdMessagesMessageIdPatchRequest = instanceOfApiV1ChatsChatIdMessagesMessageIdPatchRequest;
function ApiV1ChatsChatIdMessagesMessageIdPatchRequestFromJSON(json) {
    return ApiV1ChatsChatIdMessagesMessageIdPatchRequestFromJSONTyped(json, false);
}
exports.ApiV1ChatsChatIdMessagesMessageIdPatchRequestFromJSON = ApiV1ChatsChatIdMessagesMessageIdPatchRequestFromJSON;
function ApiV1ChatsChatIdMessagesMessageIdPatchRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'clientSideId': !(0, runtime_1.exists)(json, 'client_side_id') ? undefined : json['client_side_id'],
        'compressAlgorithm': !(0, runtime_1.exists)(json, 'compress_algorithm') ? undefined : json['compress_algorithm'],
        'content': !(0, runtime_1.exists)(json, 'content') ? undefined : json['content'],
        'cryptAlgorithm': !(0, runtime_1.exists)(json, 'crypt_algorithm') ? undefined : json['crypt_algorithm'],
    };
}
exports.ApiV1ChatsChatIdMessagesMessageIdPatchRequestFromJSONTyped = ApiV1ChatsChatIdMessagesMessageIdPatchRequestFromJSONTyped;
function ApiV1ChatsChatIdMessagesMessageIdPatchRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'client_side_id': value.clientSideId,
        'compress_algorithm': value.compressAlgorithm,
        'content': value.content,
        'crypt_algorithm': value.cryptAlgorithm,
    };
}
exports.ApiV1ChatsChatIdMessagesMessageIdPatchRequestToJSON = ApiV1ChatsChatIdMessagesMessageIdPatchRequestToJSON;
