"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1ChatsChatIdMessagesPostRequestAllOfToJSON = exports.ApiV1ChatsChatIdMessagesPostRequestAllOfFromJSONTyped = exports.ApiV1ChatsChatIdMessagesPostRequestAllOfFromJSON = exports.instanceOfApiV1ChatsChatIdMessagesPostRequestAllOf = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1ChatsChatIdMessagesPostRequestAllOf interface.
 */
function instanceOfApiV1ChatsChatIdMessagesPostRequestAllOf(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1ChatsChatIdMessagesPostRequestAllOf = instanceOfApiV1ChatsChatIdMessagesPostRequestAllOf;
function ApiV1ChatsChatIdMessagesPostRequestAllOfFromJSON(json) {
    return ApiV1ChatsChatIdMessagesPostRequestAllOfFromJSONTyped(json, false);
}
exports.ApiV1ChatsChatIdMessagesPostRequestAllOfFromJSON = ApiV1ChatsChatIdMessagesPostRequestAllOfFromJSON;
function ApiV1ChatsChatIdMessagesPostRequestAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'compressAlgorithm': !(0, runtime_1.exists)(json, 'compress_algorithm') ? undefined : json['compress_algorithm'],
        'content': !(0, runtime_1.exists)(json, 'content') ? undefined : json['content'],
        'cryptAlgorithm': !(0, runtime_1.exists)(json, 'crypt_algorithm') ? undefined : json['crypt_algorithm'],
        'mime': !(0, runtime_1.exists)(json, 'mime') ? undefined : json['mime'],
    };
}
exports.ApiV1ChatsChatIdMessagesPostRequestAllOfFromJSONTyped = ApiV1ChatsChatIdMessagesPostRequestAllOfFromJSONTyped;
function ApiV1ChatsChatIdMessagesPostRequestAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'compress_algorithm': value.compressAlgorithm,
        'content': value.content,
        'crypt_algorithm': value.cryptAlgorithm,
        'mime': value.mime,
    };
}
exports.ApiV1ChatsChatIdMessagesPostRequestAllOfToJSON = ApiV1ChatsChatIdMessagesPostRequestAllOfToJSON;
