"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1OtsPost200ResponseAllOfDataToJSON = exports.ApiV1OtsPost200ResponseAllOfDataFromJSONTyped = exports.ApiV1OtsPost200ResponseAllOfDataFromJSON = exports.instanceOfApiV1OtsPost200ResponseAllOfData = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1OtsPost200ResponseAllOfData interface.
 */
function instanceOfApiV1OtsPost200ResponseAllOfData(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1OtsPost200ResponseAllOfData = instanceOfApiV1OtsPost200ResponseAllOfData;
function ApiV1OtsPost200ResponseAllOfDataFromJSON(json) {
    return ApiV1OtsPost200ResponseAllOfDataFromJSONTyped(json, false);
}
exports.ApiV1OtsPost200ResponseAllOfDataFromJSON = ApiV1OtsPost200ResponseAllOfDataFromJSON;
function ApiV1OtsPost200ResponseAllOfDataFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'code': !(0, runtime_1.exists)(json, 'code') ? undefined : json['code'],
    };
}
exports.ApiV1OtsPost200ResponseAllOfDataFromJSONTyped = ApiV1OtsPost200ResponseAllOfDataFromJSONTyped;
function ApiV1OtsPost200ResponseAllOfDataToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'code': value.code,
    };
}
exports.ApiV1OtsPost200ResponseAllOfDataToJSON = ApiV1OtsPost200ResponseAllOfDataToJSON;
