"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1LoginPostRequestAllOfToJSON = exports.ApiV1LoginPostRequestAllOfFromJSONTyped = exports.ApiV1LoginPostRequestAllOfFromJSON = exports.instanceOfApiV1LoginPostRequestAllOf = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1LoginPostRequestAllOf interface.
 */
function instanceOfApiV1LoginPostRequestAllOf(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1LoginPostRequestAllOf = instanceOfApiV1LoginPostRequestAllOf;
function ApiV1LoginPostRequestAllOfFromJSON(json) {
    return ApiV1LoginPostRequestAllOfFromJSONTyped(json, false);
}
exports.ApiV1LoginPostRequestAllOfFromJSON = ApiV1LoginPostRequestAllOfFromJSON;
function ApiV1LoginPostRequestAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'login': !(0, runtime_1.exists)(json, 'login') ? undefined : json['login'],
        'password': !(0, runtime_1.exists)(json, 'password') ? undefined : json['password'],
    };
}
exports.ApiV1LoginPostRequestAllOfFromJSONTyped = ApiV1LoginPostRequestAllOfFromJSONTyped;
function ApiV1LoginPostRequestAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'login': value.login,
        'password': value.password,
    };
}
exports.ApiV1LoginPostRequestAllOfToJSON = ApiV1LoginPostRequestAllOfToJSON;
