/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ApiV1OtsCodeGet200Response
 */
export interface ApiV1OtsCodeGet200Response {
    /**
     *
     * @type {string}
     * @memberof ApiV1OtsCodeGet200Response
     */
    data?: string;
    /**
     *
     * @type {string}
     * @memberof ApiV1OtsCodeGet200Response
     */
    status?: string;
}
/**
 * Check if a given object implements the ApiV1OtsCodeGet200Response interface.
 */
export declare function instanceOfApiV1OtsCodeGet200Response(value: object): boolean;
export declare function ApiV1OtsCodeGet200ResponseFromJSON(json: any): ApiV1OtsCodeGet200Response;
export declare function ApiV1OtsCodeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1OtsCodeGet200Response;
export declare function ApiV1OtsCodeGet200ResponseToJSON(value?: ApiV1OtsCodeGet200Response | null): any;
