/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AuthSession } from './AuthSession';
/**
 *
 * @export
 * @interface ApiV1SessionsCurrentGet200Response
 */
export interface ApiV1SessionsCurrentGet200Response {
    /**
     *
     * @type {AuthSession}
     * @memberof ApiV1SessionsCurrentGet200Response
     */
    data?: AuthSession;
    /**
     *
     * @type {string}
     * @memberof ApiV1SessionsCurrentGet200Response
     */
    status?: string;
}
/**
 * Check if a given object implements the ApiV1SessionsCurrentGet200Response interface.
 */
export declare function instanceOfApiV1SessionsCurrentGet200Response(value: object): boolean;
export declare function ApiV1SessionsCurrentGet200ResponseFromJSON(json: any): ApiV1SessionsCurrentGet200Response;
export declare function ApiV1SessionsCurrentGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SessionsCurrentGet200Response;
export declare function ApiV1SessionsCurrentGet200ResponseToJSON(value?: ApiV1SessionsCurrentGet200Response | null): any;
