"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1LoginPost200ResponseDataToJSON = exports.ApiV1LoginPost200ResponseDataFromJSONTyped = exports.ApiV1LoginPost200ResponseDataFromJSON = exports.instanceOfApiV1LoginPost200ResponseData = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1LoginPost200ResponseData interface.
 */
function instanceOfApiV1LoginPost200ResponseData(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1LoginPost200ResponseData = instanceOfApiV1LoginPost200ResponseData;
function ApiV1LoginPost200ResponseDataFromJSON(json) {
    return ApiV1LoginPost200ResponseDataFromJSONTyped(json, false);
}
exports.ApiV1LoginPost200ResponseDataFromJSON = ApiV1LoginPost200ResponseDataFromJSON;
function ApiV1LoginPost200ResponseDataFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'token': !(0, runtime_1.exists)(json, 'token') ? undefined : json['token'],
    };
}
exports.ApiV1LoginPost200ResponseDataFromJSONTyped = ApiV1LoginPost200ResponseDataFromJSONTyped;
function ApiV1LoginPost200ResponseDataToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'token': value.token,
    };
}
exports.ApiV1LoginPost200ResponseDataToJSON = ApiV1LoginPost200ResponseDataToJSON;
