"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1ChatsPostRequestAllOfToJSON = exports.ApiV1ChatsPostRequestAllOfFromJSONTyped = exports.ApiV1ChatsPostRequestAllOfFromJSON = exports.instanceOfApiV1ChatsPostRequestAllOf = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1ChatsPostRequestAllOf interface.
 */
function instanceOfApiV1ChatsPostRequestAllOf(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1ChatsPostRequestAllOf = instanceOfApiV1ChatsPostRequestAllOf;
function ApiV1ChatsPostRequestAllOfFromJSON(json) {
    return ApiV1ChatsPostRequestAllOfFromJSONTyped(json, false);
}
exports.ApiV1ChatsPostRequestAllOfFromJSON = ApiV1ChatsPostRequestAllOfFromJSON;
function ApiV1ChatsPostRequestAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'name': !(0, runtime_1.exists)(json, 'name') ? undefined : json['name'],
    };
}
exports.ApiV1ChatsPostRequestAllOfFromJSONTyped = ApiV1ChatsPostRequestAllOfFromJSONTyped;
function ApiV1ChatsPostRequestAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'name': value.name,
    };
}
exports.ApiV1ChatsPostRequestAllOfToJSON = ApiV1ChatsPostRequestAllOfToJSON;
