"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1RegisterPostRequestToJSON = exports.ApiV1RegisterPostRequestFromJSONTyped = exports.ApiV1RegisterPostRequestFromJSON = exports.instanceOfApiV1RegisterPostRequest = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1RegisterPostRequest interface.
 */
function instanceOfApiV1RegisterPostRequest(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1RegisterPostRequest = instanceOfApiV1RegisterPostRequest;
function ApiV1RegisterPostRequestFromJSON(json) {
    return ApiV1RegisterPostRequestFromJSONTyped(json, false);
}
exports.ApiV1RegisterPostRequestFromJSON = ApiV1RegisterPostRequestFromJSON;
function ApiV1RegisterPostRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'login': !(0, runtime_1.exists)(json, 'login') ? undefined : json['login'],
        'name': !(0, runtime_1.exists)(json, 'name') ? undefined : json['name'],
        'password': !(0, runtime_1.exists)(json, 'password') ? undefined : json['password'],
    };
}
exports.ApiV1RegisterPostRequestFromJSONTyped = ApiV1RegisterPostRequestFromJSONTyped;
function ApiV1RegisterPostRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'login': value.login,
        'name': value.name,
        'password': value.password,
    };
}
exports.ApiV1RegisterPostRequestToJSON = ApiV1RegisterPostRequestToJSON;
