"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1LoginPost200ResponseToJSON = exports.ApiV1LoginPost200ResponseFromJSONTyped = exports.ApiV1LoginPost200ResponseFromJSON = exports.instanceOfApiV1LoginPost200Response = void 0;
const runtime_1 = require("../runtime");
const ApiV1LoginPost200ResponseAllOfData_1 = require("./ApiV1LoginPost200ResponseAllOfData");
/**
 * Check if a given object implements the ApiV1LoginPost200Response interface.
 */
function instanceOfApiV1LoginPost200Response(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1LoginPost200Response = instanceOfApiV1LoginPost200Response;
function ApiV1LoginPost200ResponseFromJSON(json) {
    return ApiV1LoginPost200ResponseFromJSONTyped(json, false);
}
exports.ApiV1LoginPost200ResponseFromJSON = ApiV1LoginPost200ResponseFromJSON;
function ApiV1LoginPost200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': !(0, runtime_1.exists)(json, 'data') ? undefined : (0, ApiV1LoginPost200ResponseAllOfData_1.ApiV1LoginPost200ResponseAllOfDataFromJSON)(json['data']),
        'status': !(0, runtime_1.exists)(json, 'status') ? undefined : json['status'],
    };
}
exports.ApiV1LoginPost200ResponseFromJSONTyped = ApiV1LoginPost200ResponseFromJSONTyped;
function ApiV1LoginPost200ResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': (0, ApiV1LoginPost200ResponseAllOfData_1.ApiV1LoginPost200ResponseAllOfDataToJSON)(value.data),
        'status': value.status,
    };
}
exports.ApiV1LoginPost200ResponseToJSON = ApiV1LoginPost200ResponseToJSON;
