"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1SubscribeGet200ResponseEventsInnerAllOfToJSON = exports.ApiV1SubscribeGet200ResponseEventsInnerAllOfFromJSONTyped = exports.ApiV1SubscribeGet200ResponseEventsInnerAllOfFromJSON = exports.instanceOfApiV1SubscribeGet200ResponseEventsInnerAllOf = void 0;
const runtime_1 = require("../runtime");
const ApiV1SubscribeGet200ResponseEventsInnerAllOfData_1 = require("./ApiV1SubscribeGet200ResponseEventsInnerAllOfData");
/**
 * Check if a given object implements the ApiV1SubscribeGet200ResponseEventsInnerAllOf interface.
 */
function instanceOfApiV1SubscribeGet200ResponseEventsInnerAllOf(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1SubscribeGet200ResponseEventsInnerAllOf = instanceOfApiV1SubscribeGet200ResponseEventsInnerAllOf;
function ApiV1SubscribeGet200ResponseEventsInnerAllOfFromJSON(json) {
    return ApiV1SubscribeGet200ResponseEventsInnerAllOfFromJSONTyped(json, false);
}
exports.ApiV1SubscribeGet200ResponseEventsInnerAllOfFromJSON = ApiV1SubscribeGet200ResponseEventsInnerAllOfFromJSON;
function ApiV1SubscribeGet200ResponseEventsInnerAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'category': !(0, runtime_1.exists)(json, 'category') ? undefined : json['category'],
        'data': !(0, runtime_1.exists)(json, 'data') ? undefined : (0, ApiV1SubscribeGet200ResponseEventsInnerAllOfData_1.ApiV1SubscribeGet200ResponseEventsInnerAllOfDataFromJSON)(json['data']),
        'timestamp': !(0, runtime_1.exists)(json, 'timestamp') ? undefined : json['timestamp'],
    };
}
exports.ApiV1SubscribeGet200ResponseEventsInnerAllOfFromJSONTyped = ApiV1SubscribeGet200ResponseEventsInnerAllOfFromJSONTyped;
function ApiV1SubscribeGet200ResponseEventsInnerAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'category': value.category,
        'data': (0, ApiV1SubscribeGet200ResponseEventsInnerAllOfData_1.ApiV1SubscribeGet200ResponseEventsInnerAllOfDataToJSON)(value.data),
        'timestamp': value.timestamp,
    };
}
exports.ApiV1SubscribeGet200ResponseEventsInnerAllOfToJSON = ApiV1SubscribeGet200ResponseEventsInnerAllOfToJSON;
