"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1ChatsChatIdMessagesGet200ResponseToJSON = exports.ApiV1ChatsChatIdMessagesGet200ResponseFromJSONTyped = exports.ApiV1ChatsChatIdMessagesGet200ResponseFromJSON = exports.instanceOfApiV1ChatsChatIdMessagesGet200Response = void 0;
const runtime_1 = require("../runtime");
const MessageMessage_1 = require("./MessageMessage");
/**
 * Check if a given object implements the ApiV1ChatsChatIdMessagesGet200Response interface.
 */
function instanceOfApiV1ChatsChatIdMessagesGet200Response(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1ChatsChatIdMessagesGet200Response = instanceOfApiV1ChatsChatIdMessagesGet200Response;
function ApiV1ChatsChatIdMessagesGet200ResponseFromJSON(json) {
    return ApiV1ChatsChatIdMessagesGet200ResponseFromJSONTyped(json, false);
}
exports.ApiV1ChatsChatIdMessagesGet200ResponseFromJSON = ApiV1ChatsChatIdMessagesGet200ResponseFromJSON;
function ApiV1ChatsChatIdMessagesGet200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': !(0, runtime_1.exists)(json, 'data') ? undefined : (json['data'].map(MessageMessage_1.MessageMessageFromJSON)),
        'status': !(0, runtime_1.exists)(json, 'status') ? undefined : json['status'],
    };
}
exports.ApiV1ChatsChatIdMessagesGet200ResponseFromJSONTyped = ApiV1ChatsChatIdMessagesGet200ResponseFromJSONTyped;
function ApiV1ChatsChatIdMessagesGet200ResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': value.data === undefined ? undefined : (value.data.map(MessageMessage_1.MessageMessageToJSON)),
        'status': value.status,
    };
}
exports.ApiV1ChatsChatIdMessagesGet200ResponseToJSON = ApiV1ChatsChatIdMessagesGet200ResponseToJSON;
