/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ApiV1SubscribeGet200ResponseAllOfEventsInner } from './ApiV1SubscribeGet200ResponseAllOfEventsInner';
/**
 *
 * @export
 * @interface ApiV1SubscribeGet200Response
 */
export interface ApiV1SubscribeGet200Response {
    /**
     *
     * @type {Array<ApiV1SubscribeGet200ResponseAllOfEventsInner>}
     * @memberof ApiV1SubscribeGet200Response
     */
    events?: Array<ApiV1SubscribeGet200ResponseAllOfEventsInner>;
}
/**
 * Check if a given object implements the ApiV1SubscribeGet200Response interface.
 */
export declare function instanceOfApiV1SubscribeGet200Response(value: object): boolean;
export declare function ApiV1SubscribeGet200ResponseFromJSON(json: any): ApiV1SubscribeGet200Response;
export declare function ApiV1SubscribeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SubscribeGet200Response;
export declare function ApiV1SubscribeGet200ResponseToJSON(value?: ApiV1SubscribeGet200Response | null): any;
