"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1PushWebServerPublicKeyGet200ResponseToJSON = exports.ApiV1PushWebServerPublicKeyGet200ResponseFromJSONTyped = exports.ApiV1PushWebServerPublicKeyGet200ResponseFromJSON = exports.instanceOfApiV1PushWebServerPublicKeyGet200Response = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1PushWebServerPublicKeyGet200Response interface.
 */
function instanceOfApiV1PushWebServerPublicKeyGet200Response(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1PushWebServerPublicKeyGet200Response = instanceOfApiV1PushWebServerPublicKeyGet200Response;
function ApiV1PushWebServerPublicKeyGet200ResponseFromJSON(json) {
    return ApiV1PushWebServerPublicKeyGet200ResponseFromJSONTyped(json, false);
}
exports.ApiV1PushWebServerPublicKeyGet200ResponseFromJSON = ApiV1PushWebServerPublicKeyGet200ResponseFromJSON;
function ApiV1PushWebServerPublicKeyGet200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': !(0, runtime_1.exists)(json, 'data') ? undefined : json['data'],
        'fiberMap': !(0, runtime_1.exists)(json, 'fiber.Map') ? undefined : json['fiber.Map'],
        'status': !(0, runtime_1.exists)(json, 'status') ? undefined : json['status'],
    };
}
exports.ApiV1PushWebServerPublicKeyGet200ResponseFromJSONTyped = ApiV1PushWebServerPublicKeyGet200ResponseFromJSONTyped;
function ApiV1PushWebServerPublicKeyGet200ResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': value.data,
        'fiber.Map': value.fiberMap,
        'status': value.status,
    };
}
exports.ApiV1PushWebServerPublicKeyGet200ResponseToJSON = ApiV1PushWebServerPublicKeyGet200ResponseToJSON;
