/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AuthPushSubscription } from './AuthPushSubscription';
/**
 *
 * @export
 * @interface ApiV1PushWebGet200Response
 */
export interface ApiV1PushWebGet200Response {
    /**
     *
     * @type {Array<AuthPushSubscription>}
     * @memberof ApiV1PushWebGet200Response
     */
    data?: Array<AuthPushSubscription>;
    /**
     *
     * @type {string}
     * @memberof ApiV1PushWebGet200Response
     */
    status?: string;
}
/**
 * Check if a given object implements the ApiV1PushWebGet200Response interface.
 */
export declare function instanceOfApiV1PushWebGet200Response(value: object): boolean;
export declare function ApiV1PushWebGet200ResponseFromJSON(json: any): ApiV1PushWebGet200Response;
export declare function ApiV1PushWebGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1PushWebGet200Response;
export declare function ApiV1PushWebGet200ResponseToJSON(value?: ApiV1PushWebGet200Response | null): any;
