/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ApiV1ChatsPostRequestAllOf
 */
export interface ApiV1ChatsPostRequestAllOf {
    /**
     *
     * @type {string}
     * @memberof ApiV1ChatsPostRequestAllOf
     */
    name?: string;
}
/**
 * Check if a given object implements the ApiV1ChatsPostRequestAllOf interface.
 */
export declare function instanceOfApiV1ChatsPostRequestAllOf(value: object): boolean;
export declare function ApiV1ChatsPostRequestAllOfFromJSON(json: any): ApiV1ChatsPostRequestAllOf;
export declare function ApiV1ChatsPostRequestAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatsPostRequestAllOf;
export declare function ApiV1ChatsPostRequestAllOfToJSON(value?: ApiV1ChatsPostRequestAllOf | null): any;
