"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1ChatsChatIdMessagesPost200ResponseToJSON = exports.ApiV1ChatsChatIdMessagesPost200ResponseFromJSONTyped = exports.ApiV1ChatsChatIdMessagesPost200ResponseFromJSON = exports.instanceOfApiV1ChatsChatIdMessagesPost200Response = void 0;
const runtime_1 = require("../runtime");
const MessageMessage_1 = require("./MessageMessage");
/**
 * Check if a given object implements the ApiV1ChatsChatIdMessagesPost200Response interface.
 */
function instanceOfApiV1ChatsChatIdMessagesPost200Response(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1ChatsChatIdMessagesPost200Response = instanceOfApiV1ChatsChatIdMessagesPost200Response;
function ApiV1ChatsChatIdMessagesPost200ResponseFromJSON(json) {
    return ApiV1ChatsChatIdMessagesPost200ResponseFromJSONTyped(json, false);
}
exports.ApiV1ChatsChatIdMessagesPost200ResponseFromJSON = ApiV1ChatsChatIdMessagesPost200ResponseFromJSON;
function ApiV1ChatsChatIdMessagesPost200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': !(0, runtime_1.exists)(json, 'data') ? undefined : (0, MessageMessage_1.MessageMessageFromJSON)(json['data']),
        'status': !(0, runtime_1.exists)(json, 'status') ? undefined : json['status'],
    };
}
exports.ApiV1ChatsChatIdMessagesPost200ResponseFromJSONTyped = ApiV1ChatsChatIdMessagesPost200ResponseFromJSONTyped;
function ApiV1ChatsChatIdMessagesPost200ResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': (0, MessageMessage_1.MessageMessageToJSON)(value.data),
        'status': value.status,
    };
}
exports.ApiV1ChatsChatIdMessagesPost200ResponseToJSON = ApiV1ChatsChatIdMessagesPost200ResponseToJSON;
