/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ApiV1ChatsChatIdInvitePostRequest
 */
export interface ApiV1ChatsChatIdInvitePostRequest {
    /**
     *
     * @type {string}
     * @memberof ApiV1ChatsChatIdInvitePostRequest
     */
    login?: string;
}
/**
 * Check if a given object implements the ApiV1ChatsChatIdInvitePostRequest interface.
 */
export declare function instanceOfApiV1ChatsChatIdInvitePostRequest(value: object): boolean;
export declare function ApiV1ChatsChatIdInvitePostRequestFromJSON(json: any): ApiV1ChatsChatIdInvitePostRequest;
export declare function ApiV1ChatsChatIdInvitePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatsChatIdInvitePostRequest;
export declare function ApiV1ChatsChatIdInvitePostRequestToJSON(value?: ApiV1ChatsChatIdInvitePostRequest | null): any;
