"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1SessionsCurrentGet200ResponseToJSON = exports.ApiV1SessionsCurrentGet200ResponseFromJSONTyped = exports.ApiV1SessionsCurrentGet200ResponseFromJSON = exports.instanceOfApiV1SessionsCurrentGet200Response = void 0;
const runtime_1 = require("../runtime");
const AuthSession_1 = require("./AuthSession");
/**
 * Check if a given object implements the ApiV1SessionsCurrentGet200Response interface.
 */
function instanceOfApiV1SessionsCurrentGet200Response(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1SessionsCurrentGet200Response = instanceOfApiV1SessionsCurrentGet200Response;
function ApiV1SessionsCurrentGet200ResponseFromJSON(json) {
    return ApiV1SessionsCurrentGet200ResponseFromJSONTyped(json, false);
}
exports.ApiV1SessionsCurrentGet200ResponseFromJSON = ApiV1SessionsCurrentGet200ResponseFromJSON;
function ApiV1SessionsCurrentGet200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': !(0, runtime_1.exists)(json, 'data') ? undefined : (0, AuthSession_1.AuthSessionFromJSON)(json['data']),
        'fiberMap': !(0, runtime_1.exists)(json, 'fiber.Map') ? undefined : json['fiber.Map'],
        'status': !(0, runtime_1.exists)(json, 'status') ? undefined : json['status'],
    };
}
exports.ApiV1SessionsCurrentGet200ResponseFromJSONTyped = ApiV1SessionsCurrentGet200ResponseFromJSONTyped;
function ApiV1SessionsCurrentGet200ResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': (0, AuthSession_1.AuthSessionToJSON)(value.data),
        'fiber.Map': value.fiberMap,
        'status': value.status,
    };
}
exports.ApiV1SessionsCurrentGet200ResponseToJSON = ApiV1SessionsCurrentGet200ResponseToJSON;
