/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ApiV1OtsPostRequest
 */
export interface ApiV1OtsPostRequest {
    /**
     *
     * @type {string}
     * @memberof ApiV1OtsPostRequest
     */
    data?: string;
}
/**
 * Check if a given object implements the ApiV1OtsPostRequest interface.
 */
export declare function instanceOfApiV1OtsPostRequest(value: object): boolean;
export declare function ApiV1OtsPostRequestFromJSON(json: any): ApiV1OtsPostRequest;
export declare function ApiV1OtsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1OtsPostRequest;
export declare function ApiV1OtsPostRequestToJSON(value?: ApiV1OtsPostRequest | null): any;
