"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1OtsPost200ResponseToJSON = exports.ApiV1OtsPost200ResponseFromJSONTyped = exports.ApiV1OtsPost200ResponseFromJSON = exports.instanceOfApiV1OtsPost200Response = void 0;
const runtime_1 = require("../runtime");
const ApiV1OtsPost200ResponseAllOfData_1 = require("./ApiV1OtsPost200ResponseAllOfData");
/**
 * Check if a given object implements the ApiV1OtsPost200Response interface.
 */
function instanceOfApiV1OtsPost200Response(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1OtsPost200Response = instanceOfApiV1OtsPost200Response;
function ApiV1OtsPost200ResponseFromJSON(json) {
    return ApiV1OtsPost200ResponseFromJSONTyped(json, false);
}
exports.ApiV1OtsPost200ResponseFromJSON = ApiV1OtsPost200ResponseFromJSON;
function ApiV1OtsPost200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': !(0, runtime_1.exists)(json, 'data') ? undefined : (0, ApiV1OtsPost200ResponseAllOfData_1.ApiV1OtsPost200ResponseAllOfDataFromJSON)(json['data']),
        'status': !(0, runtime_1.exists)(json, 'status') ? undefined : json['status'],
    };
}
exports.ApiV1OtsPost200ResponseFromJSONTyped = ApiV1OtsPost200ResponseFromJSONTyped;
function ApiV1OtsPost200ResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': (0, ApiV1OtsPost200ResponseAllOfData_1.ApiV1OtsPost200ResponseAllOfDataToJSON)(value.data),
        'status': value.status,
    };
}
exports.ApiV1OtsPost200ResponseToJSON = ApiV1OtsPost200ResponseToJSON;
