/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ApiV1ChatsChatIdInvitePostRequestAllOf
 */
export interface ApiV1ChatsChatIdInvitePostRequestAllOf {
    /**
     *
     * @type {string}
     * @memberof ApiV1ChatsChatIdInvitePostRequestAllOf
     */
    login?: string;
}
/**
 * Check if a given object implements the ApiV1ChatsChatIdInvitePostRequestAllOf interface.
 */
export declare function instanceOfApiV1ChatsChatIdInvitePostRequestAllOf(value: object): boolean;
export declare function ApiV1ChatsChatIdInvitePostRequestAllOfFromJSON(json: any): ApiV1ChatsChatIdInvitePostRequestAllOf;
export declare function ApiV1ChatsChatIdInvitePostRequestAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatsChatIdInvitePostRequestAllOf;
export declare function ApiV1ChatsChatIdInvitePostRequestAllOfToJSON(value?: ApiV1ChatsChatIdInvitePostRequestAllOf | null): any;
