"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiV1LoginPostRequestToJSON = exports.ApiV1LoginPostRequestFromJSONTyped = exports.ApiV1LoginPostRequestFromJSON = exports.instanceOfApiV1LoginPostRequest = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ApiV1LoginPostRequest interface.
 */
function instanceOfApiV1LoginPostRequest(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfApiV1LoginPostRequest = instanceOfApiV1LoginPostRequest;
function ApiV1LoginPostRequestFromJSON(json) {
    return ApiV1LoginPostRequestFromJSONTyped(json, false);
}
exports.ApiV1LoginPostRequestFromJSON = ApiV1LoginPostRequestFromJSON;
function ApiV1LoginPostRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'login': !(0, runtime_1.exists)(json, 'login') ? undefined : json['login'],
        'password': !(0, runtime_1.exists)(json, 'password') ? undefined : json['password'],
    };
}
exports.ApiV1LoginPostRequestFromJSONTyped = ApiV1LoginPostRequestFromJSONTyped;
function ApiV1LoginPostRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'login': value.login,
        'password': value.password,
    };
}
exports.ApiV1LoginPostRequestToJSON = ApiV1LoginPostRequestToJSON;
