"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthUserToJSON = exports.AuthUserFromJSONTyped = exports.AuthUserFromJSON = exports.instanceOfAuthUser = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the AuthUser interface.
 */
function instanceOfAuthUser(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfAuthUser = instanceOfAuthUser;
function AuthUserFromJSON(json) {
    return AuthUserFromJSONTyped(json, false);
}
exports.AuthUserFromJSON = AuthUserFromJSON;
function AuthUserFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': !(0, runtime_1.exists)(json, 'id') ? undefined : json['id'],
        'login': !(0, runtime_1.exists)(json, 'login') ? undefined : json['login'],
        'name': !(0, runtime_1.exists)(json, 'name') ? undefined : json['name'],
    };
}
exports.AuthUserFromJSONTyped = AuthUserFromJSONTyped;
function AuthUserToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'login': value.login,
        'name': value.name,
    };
}
exports.AuthUserToJSON = AuthUserToJSON;
