/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AuthPushSubscriptionType } from './AuthPushSubscriptionType';
/**
 *
 * @export
 * @interface AuthPushSubscription
 */
export interface AuthPushSubscription {
    /**
     *
     * @type {string}
     * @memberof AuthPushSubscription
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof AuthPushSubscription
     */
    sessionId?: string;
    /**
     *
     * @type {AuthPushSubscriptionType}
     * @memberof AuthPushSubscription
     */
    type?: AuthPushSubscriptionType;
}
/**
 * Check if a given object implements the AuthPushSubscription interface.
 */
export declare function instanceOfAuthPushSubscription(value: object): boolean;
export declare function AuthPushSubscriptionFromJSON(json: any): AuthPushSubscription;
export declare function AuthPushSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthPushSubscription;
export declare function AuthPushSubscriptionToJSON(value?: AuthPushSubscription | null): any;
