/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AuthUser } from './AuthUser';
/**
 *
 * @export
 * @interface AuthSession
 */
export interface AuthSession {
    /**
     *
     * @type {string}
     * @memberof AuthSession
     */
    agent?: string;
    /**
     *
     * @type {string}
     * @memberof AuthSession
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof AuthSession
     */
    ip?: string;
    /**
     *
     * @type {AuthUser}
     * @memberof AuthSession
     */
    user?: AuthUser;
}
/**
 * Check if a given object implements the AuthSession interface.
 */
export declare function instanceOfAuthSession(value: object): boolean;
export declare function AuthSessionFromJSON(json: any): AuthSession;
export declare function AuthSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSession;
export declare function AuthSessionToJSON(value?: AuthSession | null): any;
