"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthPushSubscriptionTypeToJSON = exports.AuthPushSubscriptionTypeFromJSONTyped = exports.AuthPushSubscriptionTypeFromJSON = exports.AuthPushSubscriptionType = void 0;
/**
 *
 * @export
 */
exports.AuthPushSubscriptionType = {
    Web: 'web'
};
function AuthPushSubscriptionTypeFromJSON(json) {
    return AuthPushSubscriptionTypeFromJSONTyped(json, false);
}
exports.AuthPushSubscriptionTypeFromJSON = AuthPushSubscriptionTypeFromJSON;
function AuthPushSubscriptionTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.AuthPushSubscriptionTypeFromJSONTyped = AuthPushSubscriptionTypeFromJSONTyped;
function AuthPushSubscriptionTypeToJSON(value) {
    return value;
}
exports.AuthPushSubscriptionTypeToJSON = AuthPushSubscriptionTypeToJSON;
