"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthSessionToJSON = exports.AuthSessionFromJSONTyped = exports.AuthSessionFromJSON = exports.instanceOfAuthSession = void 0;
const runtime_1 = require("../runtime");
const AuthUser_1 = require("./AuthUser");
/**
 * Check if a given object implements the AuthSession interface.
 */
function instanceOfAuthSession(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfAuthSession = instanceOfAuthSession;
function AuthSessionFromJSON(json) {
    return AuthSessionFromJSONTyped(json, false);
}
exports.AuthSessionFromJSON = AuthSessionFromJSON;
function AuthSessionFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'agent': !(0, runtime_1.exists)(json, 'agent') ? undefined : json['agent'],
        'id': !(0, runtime_1.exists)(json, 'id') ? undefined : json['id'],
        'ip': !(0, runtime_1.exists)(json, 'ip') ? undefined : json['ip'],
        'user': !(0, runtime_1.exists)(json, 'user') ? undefined : (0, AuthUser_1.AuthUserFromJSON)(json['user']),
    };
}
exports.AuthSessionFromJSONTyped = AuthSessionFromJSONTyped;
function AuthSessionToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'agent': value.agent,
        'id': value.id,
        'ip': value.ip,
        'user': (0, AuthUser_1.AuthUserToJSON)(value.user),
    };
}
exports.AuthSessionToJSON = AuthSessionToJSON;
