/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 */
export declare const AuthPushSubscriptionType: {
    readonly Web: "web";
};
export type AuthPushSubscriptionType = typeof AuthPushSubscriptionType[keyof typeof AuthPushSubscriptionType];
export declare function AuthPushSubscriptionTypeFromJSON(json: any): AuthPushSubscriptionType;
export declare function AuthPushSubscriptionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthPushSubscriptionType;
export declare function AuthPushSubscriptionTypeToJSON(value?: AuthPushSubscriptionType | null): any;
