"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthPushSubscriptionToJSON = exports.AuthPushSubscriptionFromJSONTyped = exports.AuthPushSubscriptionFromJSON = exports.instanceOfAuthPushSubscription = void 0;
const runtime_1 = require("../runtime");
const AuthPushSubscriptionType_1 = require("./AuthPushSubscriptionType");
/**
 * Check if a given object implements the AuthPushSubscription interface.
 */
function instanceOfAuthPushSubscription(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfAuthPushSubscription = instanceOfAuthPushSubscription;
function AuthPushSubscriptionFromJSON(json) {
    return AuthPushSubscriptionFromJSONTyped(json, false);
}
exports.AuthPushSubscriptionFromJSON = AuthPushSubscriptionFromJSON;
function AuthPushSubscriptionFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': !(0, runtime_1.exists)(json, 'id') ? undefined : json['id'],
        'sessionId': !(0, runtime_1.exists)(json, 'session_id') ? undefined : json['session_id'],
        'type': !(0, runtime_1.exists)(json, 'type') ? undefined : (0, AuthPushSubscriptionType_1.AuthPushSubscriptionTypeFromJSON)(json['type']),
    };
}
exports.AuthPushSubscriptionFromJSONTyped = AuthPushSubscriptionFromJSONTyped;
function AuthPushSubscriptionToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'session_id': value.sessionId,
        'type': (0, AuthPushSubscriptionType_1.AuthPushSubscriptionTypeToJSON)(value.type),
    };
}
exports.AuthPushSubscriptionToJSON = AuthPushSubscriptionToJSON;
