/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AuthUser } from './AuthUser';
/**
 *
 * @export
 * @interface ChatChat
 */
export interface ChatChat {
    /**
     *
     * @type {AuthUser}
     * @memberof ChatChat
     */
    creator?: AuthUser;
    /**
     *
     * @type {string}
     * @memberof ChatChat
     */
    id?: string;
    /**
     *
     * @type {Array<AuthUser>}
     * @memberof ChatChat
     */
    members?: Array<AuthUser>;
    /**
     *
     * @type {string}
     * @memberof ChatChat
     */
    name?: string;
}
/**
 * Check if a given object implements the ChatChat interface.
 */
export declare function instanceOfChatChat(value: object): boolean;
export declare function ChatChatFromJSON(json: any): ChatChat;
export declare function ChatChatFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatChat;
export declare function ChatChatToJSON(value?: ChatChat | null): any;
