"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChatChatToJSON = exports.ChatChatFromJSONTyped = exports.ChatChatFromJSON = exports.instanceOfChatChat = void 0;
const runtime_1 = require("../runtime");
const AuthUser_1 = require("./AuthUser");
/**
 * Check if a given object implements the ChatChat interface.
 */
function instanceOfChatChat(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfChatChat = instanceOfChatChat;
function ChatChatFromJSON(json) {
    return ChatChatFromJSONTyped(json, false);
}
exports.ChatChatFromJSON = ChatChatFromJSON;
function ChatChatFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'creator': !(0, runtime_1.exists)(json, 'creator') ? undefined : (0, AuthUser_1.AuthUserFromJSON)(json['creator']),
        'id': !(0, runtime_1.exists)(json, 'id') ? undefined : json['id'],
        'members': !(0, runtime_1.exists)(json, 'members') ? undefined : (json['members'].map(AuthUser_1.AuthUserFromJSON)),
        'name': !(0, runtime_1.exists)(json, 'name') ? undefined : json['name'],
    };
}
exports.ChatChatFromJSONTyped = ChatChatFromJSONTyped;
function ChatChatToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'creator': (0, AuthUser_1.AuthUserToJSON)(value.creator),
        'id': value.id,
        'members': value.members === undefined ? undefined : (value.members.map(AuthUser_1.AuthUserToJSON)),
        'name': value.name,
    };
}
exports.ChatChatToJSON = ChatChatToJSON;
