"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FileAccessorToJSON = exports.FileAccessorFromJSONTyped = exports.FileAccessorFromJSON = exports.FileAccessor = void 0;
/**
 *
 * @export
 */
exports.FileAccessor = {
    Public: 'public',
    Private: 'private'
};
function FileAccessorFromJSON(json) {
    return FileAccessorFromJSONTyped(json, false);
}
exports.FileAccessorFromJSON = FileAccessorFromJSON;
function FileAccessorFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.FileAccessorFromJSONTyped = FileAccessorFromJSONTyped;
function FileAccessorToJSON(value) {
    return value;
}
exports.FileAccessorToJSON = FileAccessorToJSON;
