/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 */
export declare const FileAccessor: {
    readonly Public: "public";
    readonly Private: "private";
};
export type FileAccessor = typeof FileAccessor[keyof typeof FileAccessor];
export declare function FileAccessorFromJSON(json: any): FileAccessor;
export declare function FileAccessorFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileAccessor;
export declare function FileAccessorToJSON(value?: FileAccessor | null): any;
