/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { FileAccessor } from './FileAccessor';
/**
 *
 * @export
 * @interface FileMeta
 */
export interface FileMeta {
    /**
     *
     * @type {FileAccessor}
     * @memberof FileMeta
     */
    accessor?: FileAccessor;
    /**
     *
     * @type {string}
     * @memberof FileMeta
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof FileMeta
     */
    messageId?: string;
    /**
     *
     * @type {string}
     * @memberof FileMeta
     */
    mime?: string;
    /**
     *
     * @type {number}
     * @memberof FileMeta
     */
    size?: number;
}
/**
 * Check if a given object implements the FileMeta interface.
 */
export declare function instanceOfFileMeta(value: object): boolean;
export declare function FileMetaFromJSON(json: any): FileMeta;
export declare function FileMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileMeta;
export declare function FileMetaToJSON(value?: FileMeta | null): any;
