"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FileMetaToJSON = exports.FileMetaFromJSONTyped = exports.FileMetaFromJSON = exports.instanceOfFileMeta = void 0;
const runtime_1 = require("../runtime");
const FileAccessor_1 = require("./FileAccessor");
/**
 * Check if a given object implements the FileMeta interface.
 */
function instanceOfFileMeta(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfFileMeta = instanceOfFileMeta;
function FileMetaFromJSON(json) {
    return FileMetaFromJSONTyped(json, false);
}
exports.FileMetaFromJSON = FileMetaFromJSON;
function FileMetaFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'accessor': !(0, runtime_1.exists)(json, 'accessor') ? undefined : (0, FileAccessor_1.FileAccessorFromJSON)(json['accessor']),
        'id': !(0, runtime_1.exists)(json, 'id') ? undefined : json['id'],
        'messageId': !(0, runtime_1.exists)(json, 'message_id') ? undefined : json['message_id'],
        'mime': !(0, runtime_1.exists)(json, 'mime') ? undefined : json['mime'],
        'size': !(0, runtime_1.exists)(json, 'size') ? undefined : json['size'],
    };
}
exports.FileMetaFromJSONTyped = FileMetaFromJSONTyped;
function FileMetaToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'accessor': (0, FileAccessor_1.FileAccessorToJSON)(value.accessor),
        'id': value.id,
        'message_id': value.messageId,
        'mime': value.mime,
        'size': value.size,
    };
}
exports.FileMetaToJSON = FileMetaToJSON;
