/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Get200ResponseAllOfData } from './Get200ResponseAllOfData';
/**
 *
 * @export
 * @interface Get200Response
 */
export interface Get200Response {
    /**
     *
     * @type {Get200ResponseAllOfData}
     * @memberof Get200Response
     */
    data?: Get200ResponseAllOfData;
    /**
     *
     * @type {string}
     * @memberof Get200Response
     */
    status?: string;
}
/**
 * Check if a given object implements the Get200Response interface.
 */
export declare function instanceOfGet200Response(value: object): boolean;
export declare function Get200ResponseFromJSON(json: any): Get200Response;
export declare function Get200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Get200Response;
export declare function Get200ResponseToJSON(value?: Get200Response | null): any;
