"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Get200ResponseDataToJSON = exports.Get200ResponseDataFromJSONTyped = exports.Get200ResponseDataFromJSON = exports.instanceOfGet200ResponseData = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the Get200ResponseData interface.
 */
function instanceOfGet200ResponseData(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfGet200ResponseData = instanceOfGet200ResponseData;
function Get200ResponseDataFromJSON(json) {
    return Get200ResponseDataFromJSONTyped(json, false);
}
exports.Get200ResponseDataFromJSON = Get200ResponseDataFromJSON;
function Get200ResponseDataFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'message': !(0, runtime_1.exists)(json, 'message') ? undefined : json['message'],
    };
}
exports.Get200ResponseDataFromJSONTyped = Get200ResponseDataFromJSONTyped;
function Get200ResponseDataToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'message': value.message,
    };
}
exports.Get200ResponseDataToJSON = Get200ResponseDataToJSON;
