"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Get200ResponseToJSON = exports.Get200ResponseFromJSONTyped = exports.Get200ResponseFromJSON = exports.instanceOfGet200Response = void 0;
const runtime_1 = require("../runtime");
const Get200ResponseData_1 = require("./Get200ResponseData");
/**
 * Check if a given object implements the Get200Response interface.
 */
function instanceOfGet200Response(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfGet200Response = instanceOfGet200Response;
function Get200ResponseFromJSON(json) {
    return Get200ResponseFromJSONTyped(json, false);
}
exports.Get200ResponseFromJSON = Get200ResponseFromJSON;
function Get200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': !(0, runtime_1.exists)(json, 'data') ? undefined : (0, Get200ResponseData_1.Get200ResponseDataFromJSON)(json['data']),
        'fiberMap': !(0, runtime_1.exists)(json, 'fiber.Map') ? undefined : json['fiber.Map'],
        'status': !(0, runtime_1.exists)(json, 'status') ? undefined : json['status'],
    };
}
exports.Get200ResponseFromJSONTyped = Get200ResponseFromJSONTyped;
function Get200ResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': (0, Get200ResponseData_1.Get200ResponseDataToJSON)(value.data),
        'fiber.Map': value.fiberMap,
        'status': value.status,
    };
}
exports.Get200ResponseToJSON = Get200ResponseToJSON;
