/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Get200ResponseDataAllOf
 */
export interface Get200ResponseDataAllOf {
    /**
     *
     * @type {string}
     * @memberof Get200ResponseDataAllOf
     */
    message?: string;
}
/**
 * Check if a given object implements the Get200ResponseDataAllOf interface.
 */
export declare function instanceOfGet200ResponseDataAllOf(value: object): boolean;
export declare function Get200ResponseDataAllOfFromJSON(json: any): Get200ResponseDataAllOf;
export declare function Get200ResponseDataAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): Get200ResponseDataAllOf;
export declare function Get200ResponseDataAllOfToJSON(value?: Get200ResponseDataAllOf | null): any;
