"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Get200ResponseDataAllOfToJSON = exports.Get200ResponseDataAllOfFromJSONTyped = exports.Get200ResponseDataAllOfFromJSON = exports.instanceOfGet200ResponseDataAllOf = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the Get200ResponseDataAllOf interface.
 */
function instanceOfGet200ResponseDataAllOf(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfGet200ResponseDataAllOf = instanceOfGet200ResponseDataAllOf;
function Get200ResponseDataAllOfFromJSON(json) {
    return Get200ResponseDataAllOfFromJSONTyped(json, false);
}
exports.Get200ResponseDataAllOfFromJSON = Get200ResponseDataAllOfFromJSON;
function Get200ResponseDataAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'message': !(0, runtime_1.exists)(json, 'message') ? undefined : json['message'],
    };
}
exports.Get200ResponseDataAllOfFromJSONTyped = Get200ResponseDataAllOfFromJSONTyped;
function Get200ResponseDataAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'message': value.message,
    };
}
exports.Get200ResponseDataAllOfToJSON = Get200ResponseDataAllOfToJSON;
