"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Get404ResponseToJSON = exports.Get404ResponseFromJSONTyped = exports.Get404ResponseFromJSON = exports.instanceOfGet404Response = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the Get404Response interface.
 */
function instanceOfGet404Response(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfGet404Response = instanceOfGet404Response;
function Get404ResponseFromJSON(json) {
    return Get404ResponseFromJSONTyped(json, false);
}
exports.Get404ResponseFromJSON = Get404ResponseFromJSON;
function Get404ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'fiberMap': !(0, runtime_1.exists)(json, 'fiber.Map') ? undefined : json['fiber.Map'],
        'status': !(0, runtime_1.exists)(json, 'status') ? undefined : json['status'],
        'type': !(0, runtime_1.exists)(json, 'type') ? undefined : json['type'],
    };
}
exports.Get404ResponseFromJSONTyped = Get404ResponseFromJSONTyped;
function Get404ResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'fiber.Map': value.fiberMap,
        'status': value.status,
        'type': value.type,
    };
}
exports.Get404ResponseToJSON = Get404ResponseToJSON;
