/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Get404Response
 */
export interface Get404Response {
    /**
     *
     * @type {string}
     * @memberof Get404Response
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof Get404Response
     */
    type?: string;
}
/**
 * Check if a given object implements the Get404Response interface.
 */
export declare function instanceOfGet404Response(value: object): boolean;
export declare function Get404ResponseFromJSON(json: any): Get404Response;
export declare function Get404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Get404Response;
export declare function Get404ResponseToJSON(value?: Get404Response | null): any;
