/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface VersionGet200ResponseDataAllOf
 */
export interface VersionGet200ResponseDataAllOf {
    /**
     *
     * @type {number}
     * @memberof VersionGet200ResponseDataAllOf
     */
    build?: number;
    /**
     *
     * @type {string}
     * @memberof VersionGet200ResponseDataAllOf
     */
    subject?: string;
    /**
     *
     * @type {string}
     * @memberof VersionGet200ResponseDataAllOf
     */
    version?: string;
}
/**
 * Check if a given object implements the VersionGet200ResponseDataAllOf interface.
 */
export declare function instanceOfVersionGet200ResponseDataAllOf(value: object): boolean;
export declare function VersionGet200ResponseDataAllOfFromJSON(json: any): VersionGet200ResponseDataAllOf;
export declare function VersionGet200ResponseDataAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionGet200ResponseDataAllOf;
export declare function VersionGet200ResponseDataAllOfToJSON(value?: VersionGet200ResponseDataAllOf | null): any;
