"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VersionGet200ResponseToJSON = exports.VersionGet200ResponseFromJSONTyped = exports.VersionGet200ResponseFromJSON = exports.instanceOfVersionGet200Response = void 0;
const runtime_1 = require("../runtime");
const VersionGet200ResponseData_1 = require("./VersionGet200ResponseData");
/**
 * Check if a given object implements the VersionGet200Response interface.
 */
function instanceOfVersionGet200Response(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfVersionGet200Response = instanceOfVersionGet200Response;
function VersionGet200ResponseFromJSON(json) {
    return VersionGet200ResponseFromJSONTyped(json, false);
}
exports.VersionGet200ResponseFromJSON = VersionGet200ResponseFromJSON;
function VersionGet200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': !(0, runtime_1.exists)(json, 'data') ? undefined : (0, VersionGet200ResponseData_1.VersionGet200ResponseDataFromJSON)(json['data']),
        'fiberMap': !(0, runtime_1.exists)(json, 'fiber.Map') ? undefined : json['fiber.Map'],
        'status': !(0, runtime_1.exists)(json, 'status') ? undefined : json['status'],
    };
}
exports.VersionGet200ResponseFromJSONTyped = VersionGet200ResponseFromJSONTyped;
function VersionGet200ResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': (0, VersionGet200ResponseData_1.VersionGet200ResponseDataToJSON)(value.data),
        'fiber.Map': value.fiberMap,
        'status': value.status,
    };
}
exports.VersionGet200ResponseToJSON = VersionGet200ResponseToJSON;
