"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VersionGet200ResponseDataAllOfToJSON = exports.VersionGet200ResponseDataAllOfFromJSONTyped = exports.VersionGet200ResponseDataAllOfFromJSON = exports.instanceOfVersionGet200ResponseDataAllOf = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the VersionGet200ResponseDataAllOf interface.
 */
function instanceOfVersionGet200ResponseDataAllOf(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfVersionGet200ResponseDataAllOf = instanceOfVersionGet200ResponseDataAllOf;
function VersionGet200ResponseDataAllOfFromJSON(json) {
    return VersionGet200ResponseDataAllOfFromJSONTyped(json, false);
}
exports.VersionGet200ResponseDataAllOfFromJSON = VersionGet200ResponseDataAllOfFromJSON;
function VersionGet200ResponseDataAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'build': !(0, runtime_1.exists)(json, 'build') ? undefined : json['build'],
        'subject': !(0, runtime_1.exists)(json, 'subject') ? undefined : json['subject'],
        'version': !(0, runtime_1.exists)(json, 'version') ? undefined : json['version'],
    };
}
exports.VersionGet200ResponseDataAllOfFromJSONTyped = VersionGet200ResponseDataAllOfFromJSONTyped;
function VersionGet200ResponseDataAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'build': value.build,
        'subject': value.subject,
        'version': value.version,
    };
}
exports.VersionGet200ResponseDataAllOfToJSON = VersionGet200ResponseDataAllOfToJSON;
