"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VersionGet200ResponseDataToJSON = exports.VersionGet200ResponseDataFromJSONTyped = exports.VersionGet200ResponseDataFromJSON = exports.instanceOfVersionGet200ResponseData = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the VersionGet200ResponseData interface.
 */
function instanceOfVersionGet200ResponseData(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfVersionGet200ResponseData = instanceOfVersionGet200ResponseData;
function VersionGet200ResponseDataFromJSON(json) {
    return VersionGet200ResponseDataFromJSONTyped(json, false);
}
exports.VersionGet200ResponseDataFromJSON = VersionGet200ResponseDataFromJSON;
function VersionGet200ResponseDataFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'build': !(0, runtime_1.exists)(json, 'build') ? undefined : json['build'],
        'subject': !(0, runtime_1.exists)(json, 'subject') ? undefined : json['subject'],
        'version': !(0, runtime_1.exists)(json, 'version') ? undefined : json['version'],
    };
}
exports.VersionGet200ResponseDataFromJSONTyped = VersionGet200ResponseDataFromJSONTyped;
function VersionGet200ResponseDataToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'build': value.build,
        'subject': value.subject,
        'version': value.version,
    };
}
exports.VersionGet200ResponseDataToJSON = VersionGet200ResponseDataToJSON;
