/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { VersionGet200ResponseData } from './VersionGet200ResponseData';
/**
 *
 * @export
 * @interface VersionGet200Response
 */
export interface VersionGet200Response {
    /**
     *
     * @type {VersionGet200ResponseData}
     * @memberof VersionGet200Response
     */
    data?: VersionGet200ResponseData;
    /**
     *
     * @type {object}
     * @memberof VersionGet200Response
     */
    fiberMap?: object;
    /**
     *
     * @type {string}
     * @memberof VersionGet200Response
     */
    status?: string;
}
/**
 * Check if a given object implements the VersionGet200Response interface.
 */
export declare function instanceOfVersionGet200Response(value: object): boolean;
export declare function VersionGet200ResponseFromJSON(json: any): VersionGet200Response;
export declare function VersionGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionGet200Response;
export declare function VersionGet200ResponseToJSON(value?: VersionGet200Response | null): any;
