/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface VersionGet200ResponseData
 */
export interface VersionGet200ResponseData {
    /**
     *
     * @type {number}
     * @memberof VersionGet200ResponseData
     */
    build?: number;
    /**
     *
     * @type {string}
     * @memberof VersionGet200ResponseData
     */
    subject?: string;
    /**
     *
     * @type {string}
     * @memberof VersionGet200ResponseData
     */
    version?: string;
}
/**
 * Check if a given object implements the VersionGet200ResponseData interface.
 */
export declare function instanceOfVersionGet200ResponseData(value: object): boolean;
export declare function VersionGet200ResponseDataFromJSON(json: any): VersionGet200ResponseData;
export declare function VersionGet200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionGet200ResponseData;
export declare function VersionGet200ResponseDataToJSON(value?: VersionGet200ResponseData | null): any;
