/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { ApiV1LoginPost200Response, ApiV1LoginPostRequest, ApiV1RegisterPostRequest } from '../models';
export interface ApiV1LoginPostOperationRequest {
    payload: ApiV1LoginPostRequest;
}
export interface ApiV1RegisterPostOperationRequest {
    payload: ApiV1RegisterPostRequest;
}
/**
 *
 */
export declare class AuthApi extends runtime.BaseAPI {
    /**
     * Login
     */
    apiV1LoginPostRaw(requestParameters: ApiV1LoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1LoginPost200Response>>;
    /**
     * Login
     */
    apiV1LoginPost(requestParameters: ApiV1LoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1LoginPost200Response>;
    /**
     * Register
     */
    apiV1RegisterPostRaw(requestParameters: ApiV1RegisterPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1LoginPost200Response>>;
    /**
     * Register
     */
    apiV1RegisterPost(requestParameters: ApiV1RegisterPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1LoginPost200Response>;
}
