/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { ApiV1ChatsChatIdInvitePost200Response, ApiV1ChatsChatIdInvitePostRequest, ApiV1ChatsGet200Response, ApiV1ChatsPost200Response, ApiV1ChatsPostRequest } from '../models';
export interface ApiV1ChatsChatIdGetRequest {
    chatId: string;
}
export interface ApiV1ChatsChatIdInvitePostOperationRequest {
    chatId: string;
    payload: ApiV1ChatsChatIdInvitePostRequest;
}
export interface ApiV1ChatsPostOperationRequest {
    payload: ApiV1ChatsPostRequest;
}
/**
 *
 */
export declare class ChatApi extends runtime.BaseAPI {
    /**
     * Get specific existing chat where user is member
     */
    apiV1ChatsChatIdGetRaw(requestParameters: ApiV1ChatsChatIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatsPost200Response>>;
    /**
     * Get specific existing chat where user is member
     */
    apiV1ChatsChatIdGet(requestParameters: ApiV1ChatsChatIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatsPost200Response>;
    /**
     * Invite user in specific chat
     */
    apiV1ChatsChatIdInvitePostRaw(requestParameters: ApiV1ChatsChatIdInvitePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatsChatIdInvitePost200Response>>;
    /**
     * Invite user in specific chat
     */
    apiV1ChatsChatIdInvitePost(requestParameters: ApiV1ChatsChatIdInvitePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatsChatIdInvitePost200Response>;
    /**
     * List existing chat where user is member
     */
    apiV1ChatsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatsGet200Response>>;
    /**
     * List existing chat where user is member
     */
    apiV1ChatsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatsGet200Response>;
    /**
     * Create new chat
     */
    apiV1ChatsPostRaw(requestParameters: ApiV1ChatsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatsPost200Response>>;
    /**
     * Create new chat
     */
    apiV1ChatsPost(requestParameters: ApiV1ChatsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatsPost200Response>;
}
