/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { ApiV1SubscribeGet200Response } from '../models/index';
/**
 *
 */
export declare class EventsApi extends runtime.BaseAPI {
    /**
     * Long polling subscribe to events
     */
    apiV1SubscribeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1SubscribeGet200Response>>;
    /**
     * Long polling subscribe to events
     */
    apiV1SubscribeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1SubscribeGet200Response>;
}
