/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { ApiV1ChatsChatIdFilesPut200Response } from '../models/index';
export interface ApiV1ChatsChatIdFilesPutRequest {
    chatId: string;
    mime: string;
    file: object;
}
export interface ApiV1FilesPrivateChatIdFileIdGetRequest {
    chatId: string;
    fileId: string;
}
/**
 *
 */
export declare class FileApi extends runtime.BaseAPI {
    /**
     * Upload file to specific chat
     */
    apiV1ChatsChatIdFilesPutRaw(requestParameters: ApiV1ChatsChatIdFilesPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatsChatIdFilesPut200Response>>;
    /**
     * Upload file to specific chat
     */
    apiV1ChatsChatIdFilesPut(requestParameters: ApiV1ChatsChatIdFilesPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatsChatIdFilesPut200Response>;
    /**
     * Download chat file
     */
    apiV1FilesPrivateChatIdFileIdGetRaw(requestParameters: ApiV1FilesPrivateChatIdFileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;
    /**
     * Download chat file
     */
    apiV1FilesPrivateChatIdFileIdGet(requestParameters: ApiV1FilesPrivateChatIdFileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;
}
