"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessagingApi = void 0;
const runtime = require("../runtime");
const models_1 = require("../models");
/**
 *
 */
class MessagingApi extends runtime.BaseAPI {
    /**
     * Get chat messages
     */
    apiV1ChatsChatIdMessagesGetRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            if (requestParameters.chatId === null || requestParameters.chatId === undefined) {
                throw new runtime.RequiredError('chatId', 'Required parameter requestParameters.chatId was null or undefined when calling apiV1ChatsChatIdMessagesGet.');
            }
            if (requestParameters.limit === null || requestParameters.limit === undefined) {
                throw new runtime.RequiredError('limit', 'Required parameter requestParameters.limit was null or undefined when calling apiV1ChatsChatIdMessagesGet.');
            }
            const queryParameters = {};
            if (requestParameters.limit !== undefined) {
                queryParameters['limit'] = requestParameters.limit;
            }
            if (requestParameters.lastMessageId !== undefined) {
                queryParameters['last_message_id'] = requestParameters.lastMessageId;
            }
            const headerParameters = {};
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/api/v1/chats/{chat_id}/messages`.replace(`{${"chat_id"}}`, encodeURIComponent(String(requestParameters.chatId))),
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => (0, models_1.ApiV1ChatsChatIdMessagesGet200ResponseFromJSON)(jsonValue));
        });
    }
    /**
     * Get chat messages
     */
    apiV1ChatsChatIdMessagesGet(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.apiV1ChatsChatIdMessagesGetRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     * Possible crypt_algorithm: \"none\", \"aes-256-cbc\". Possible compress_algorithm: \"none\", \"zlib-deflate\". <br> Mime must be a valid mime type. Available mime type you cat find here: https://github.com/gabriel-vasile/mimetype/blob/master/supported_mimes.md
     * Send message in specific chat
     */
    apiV1ChatsChatIdMessagesPostRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            if (requestParameters.chatId === null || requestParameters.chatId === undefined) {
                throw new runtime.RequiredError('chatId', 'Required parameter requestParameters.chatId was null or undefined when calling apiV1ChatsChatIdMessagesPost.');
            }
            if (requestParameters.payload === null || requestParameters.payload === undefined) {
                throw new runtime.RequiredError('payload', 'Required parameter requestParameters.payload was null or undefined when calling apiV1ChatsChatIdMessagesPost.');
            }
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/api/v1/chats/{chat_id}/messages`.replace(`{${"chat_id"}}`, encodeURIComponent(String(requestParameters.chatId))),
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: (0, models_1.ApiV1ChatsChatIdMessagesPostRequestToJSON)(requestParameters.payload),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => (0, models_1.ApiV1ChatsChatIdMessagesPost200ResponseFromJSON)(jsonValue));
        });
    }
    /**
     * Possible crypt_algorithm: \"none\", \"aes-256-cbc\". Possible compress_algorithm: \"none\", \"zlib-deflate\". <br> Mime must be a valid mime type. Available mime type you cat find here: https://github.com/gabriel-vasile/mimetype/blob/master/supported_mimes.md
     * Send message in specific chat
     */
    apiV1ChatsChatIdMessagesPost(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.apiV1ChatsChatIdMessagesPostRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
}
exports.MessagingApi = MessagingApi;
