/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { Get200Response, VersionGet200Response } from '../models';
/**
 *
 */
export declare class MiscApi extends runtime.BaseAPI {
    /**
     * Show server hello message
     */
    rootGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Get200Response>>;
    /**
     * Show server hello message
     */
    rootGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Get200Response>;
    /**
     * Show Swagger UI
     */
    swaggerGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;
    /**
     * Show Swagger UI
     */
    swaggerGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;
    /**
     * Show server version
     */
    versionGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionGet200Response>>;
    /**
     * Show server version
     */
    versionGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionGet200Response>;
}
