/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { ApiV1OtsCodeGet200Response, ApiV1OtsPost200Response, ApiV1OtsPostRequest } from '../models/index';
export interface ApiV1OtsCodeGetRequest {
    code: string;
}
export interface ApiV1OtsPostOperationRequest {
    payload: ApiV1OtsPostRequest;
}
/**
 *
 */
export declare class OtsApi extends runtime.BaseAPI {
    /**
     * Get One-Time-Storage data
     */
    apiV1OtsCodeGetRaw(requestParameters: ApiV1OtsCodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1OtsCodeGet200Response>>;
    /**
     * Get One-Time-Storage data
     */
    apiV1OtsCodeGet(requestParameters: ApiV1OtsCodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1OtsCodeGet200Response>;
    /**
     * Create One-Time-Storage
     */
    apiV1OtsPostRaw(requestParameters: ApiV1OtsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1OtsPost200Response>>;
    /**
     * Create One-Time-Storage
     */
    apiV1OtsPost(requestParameters: ApiV1OtsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1OtsPost200Response>;
}
