"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.PushApi = void 0;
const runtime = require("../runtime");
const index_1 = require("../models/index");
/**
 *
 */
class PushApi extends runtime.BaseAPI {
    /**
     * Get Web Push Subscriptions
     */
    apiV1PushWebGetRaw(initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/api/v1/push/web`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.ApiV1PushWebGet200ResponseFromJSON)(jsonValue));
        });
    }
    /**
     * Get Web Push Subscriptions
     */
    apiV1PushWebGet(initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.apiV1PushWebGetRaw(initOverrides);
            return yield response.value();
        });
    }
    /**
     * Delete Web Push Subscription
     */
    apiV1PushWebIdDeleteRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            if (requestParameters.id === null || requestParameters.id === undefined) {
                throw new runtime.RequiredError('id', 'Required parameter requestParameters.id was null or undefined when calling apiV1PushWebIdDelete.');
            }
            const queryParameters = {};
            const headerParameters = {};
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/api/v1/push/web/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
                method: 'DELETE',
                headers: headerParameters,
                query: queryParameters,
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.ApiV1ChatsChatIdInvitePost200ResponseFromJSON)(jsonValue));
        });
    }
    /**
     * Delete Web Push Subscription
     */
    apiV1PushWebIdDelete(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.apiV1PushWebIdDeleteRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     * Retrieve VAPID public key for PUSH notification
     */
    apiV1PushWebServerPublicKeyGetRaw(initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/api/v1/push/web/server/public-key`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.ApiV1OtsCodeGet200ResponseFromJSON)(jsonValue));
        });
    }
    /**
     * Retrieve VAPID public key for PUSH notification
     */
    apiV1PushWebServerPublicKeyGet(initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.apiV1PushWebServerPublicKeyGetRaw(initOverrides);
            return yield response.value();
        });
    }
    /**
     * Subscribe to web PUSH notifications
     */
    apiV1PushWebSubscribePostRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            if (requestParameters.payload === null || requestParameters.payload === undefined) {
                throw new runtime.RequiredError('payload', 'Required parameter requestParameters.payload was null or undefined when calling apiV1PushWebSubscribePost.');
            }
            const queryParameters = {};
            const headerParameters = {};
            headerParameters['Content-Type'] = 'application/json';
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/api/v1/push/web/subscribe`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: (0, index_1.ApiV1PushWebSubscribePostRequestToJSON)(requestParameters.payload),
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.ApiV1ChatsChatIdInvitePost200ResponseFromJSON)(jsonValue));
        });
    }
    /**
     * Subscribe to web PUSH notifications
     */
    apiV1PushWebSubscribePost(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.apiV1PushWebSubscribePostRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
    /**
     * Test Web Push Subscriptions
     */
    apiV1PushWebTestPostRaw(initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/api/v1/push/web/test`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.ApiV1ChatsChatIdInvitePost200ResponseFromJSON)(jsonValue));
        });
    }
    /**
     * Test Web Push Subscriptions
     */
    apiV1PushWebTestPost(initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.apiV1PushWebTestPostRaw(initOverrides);
            return yield response.value();
        });
    }
}
exports.PushApi = PushApi;
