/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { ApiV1ChatsChatIdInvitePost200Response, ApiV1OtsCodeGet200Response, ApiV1PushWebSubscribePostRequest } from '../models/index';
export interface ApiV1PushWebIdDeleteRequest {
    id: string;
}
export interface ApiV1PushWebSubscribePostOperationRequest {
    payload: ApiV1PushWebSubscribePostRequest;
}
/**
 *
 */
export declare class PushApi extends runtime.BaseAPI {
    /**
     * Delete Web Push Subscription
     */
    apiV1PushWebIdDeleteRaw(requestParameters: ApiV1PushWebIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatsChatIdInvitePost200Response>>;
    /**
     * Delete Web Push Subscription
     */
    apiV1PushWebIdDelete(requestParameters: ApiV1PushWebIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatsChatIdInvitePost200Response>;
    /**
     * Retrieve VAPID public key for PUSH notification
     */
    apiV1PushWebServerPublicKeyGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1OtsCodeGet200Response>>;
    /**
     * Retrieve VAPID public key for PUSH notification
     */
    apiV1PushWebServerPublicKeyGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1OtsCodeGet200Response>;
    /**
     * Subscribe to web PUSH notifications
     */
    apiV1PushWebSubscribePostRaw(requestParameters: ApiV1PushWebSubscribePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatsChatIdInvitePost200Response>>;
    /**
     * Subscribe to web PUSH notifications
     */
    apiV1PushWebSubscribePost(requestParameters: ApiV1PushWebSubscribePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatsChatIdInvitePost200Response>;
    /**
     * Test Web Push Subscriptions
     */
    apiV1PushWebTestPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatsChatIdInvitePost200Response>>;
    /**
     * Test Web Push Subscriptions
     */
    apiV1PushWebTestPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatsChatIdInvitePost200Response>;
}
