/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { ApiV1ChatsChatIdInvitePost200Response, ApiV1SessionsCurrentGet200Response, ApiV1SessionsGet200Response } from '../models';
export interface ApiV1SessionsSessionIdRevokePostRequest {
    sessionId: string;
}
/**
 *
 */
export declare class UserApi extends runtime.BaseAPI {
    /**
     * Get current session of user
     */
    apiV1SessionsCurrentGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1SessionsCurrentGet200Response>>;
    /**
     * Get current session of user
     */
    apiV1SessionsCurrentGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1SessionsCurrentGet200Response>;
    /**
     * List active user sessions
     */
    apiV1SessionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1SessionsGet200Response>>;
    /**
     * List active user sessions
     */
    apiV1SessionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1SessionsGet200Response>;
    /**
     * Logout specific session
     */
    apiV1SessionsSessionIdRevokePostRaw(requestParameters: ApiV1SessionsSessionIdRevokePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatsChatIdInvitePost200Response>>;
    /**
     * Logout specific session
     */
    apiV1SessionsSessionIdRevokePost(requestParameters: ApiV1SessionsSessionIdRevokePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatsChatIdInvitePost200Response>;
}
