"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserApi = void 0;
const runtime = require("../runtime");
const index_1 = require("../models/index");
/**
 *
 */
class UserApi extends runtime.BaseAPI {
    /**
     * Get current session of user
     */
    apiV1SessionsCurrentGetRaw(initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/api/v1/sessions/current`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.ApiV1SessionsCurrentGet200ResponseFromJSON)(jsonValue));
        });
    }
    /**
     * Get current session of user
     */
    apiV1SessionsCurrentGet(initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.apiV1SessionsCurrentGetRaw(initOverrides);
            return yield response.value();
        });
    }
    /**
     * List active user sessions
     */
    apiV1SessionsGetRaw(initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const queryParameters = {};
            const headerParameters = {};
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/api/v1/sessions`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.ApiV1SessionsGet200ResponseFromJSON)(jsonValue));
        });
    }
    /**
     * List active user sessions
     */
    apiV1SessionsGet(initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.apiV1SessionsGetRaw(initOverrides);
            return yield response.value();
        });
    }
    /**
     * Logout specific session
     */
    apiV1SessionsSessionIdRevokePostRaw(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            if (requestParameters.sessionId === null || requestParameters.sessionId === undefined) {
                throw new runtime.RequiredError('sessionId', 'Required parameter requestParameters.sessionId was null or undefined when calling apiV1SessionsSessionIdRevokePost.');
            }
            const queryParameters = {};
            const headerParameters = {};
            if (this.configuration && this.configuration.apiKey) {
                headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
            }
            const response = yield this.request({
                path: `/api/v1/sessions/{session_id}/revoke`.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters.sessionId))),
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
            }, initOverrides);
            return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.ApiV1ChatsChatIdInvitePost200ResponseFromJSON)(jsonValue));
        });
    }
    /**
     * Logout specific session
     */
    apiV1SessionsSessionIdRevokePost(requestParameters, initOverrides) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield this.apiV1SessionsSessionIdRevokePostRaw(requestParameters, initOverrides);
            return yield response.value();
        });
    }
}
exports.UserApi = UserApi;
