/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV1SubscribeGet200Response,
} from '../models';
import {
    ApiV1SubscribeGet200ResponseFromJSON,
    ApiV1SubscribeGet200ResponseToJSON,
} from '../models';

/**
 * 
 */
export class EventsApi extends runtime.BaseAPI {

    /**
     * Long polling subscribe to events
     */
    async apiV1SubscribeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1SubscribeGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/subscribe`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1SubscribeGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Long polling subscribe to events
     */
    async apiV1SubscribeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1SubscribeGet200Response> {
        const response = await this.apiV1SubscribeGetRaw(initOverrides);
        return await response.value();
    }

}
