/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FileMeta } from './FileMeta';
import {
    FileMetaFromJSON,
    FileMetaFromJSONTyped,
    FileMetaToJSON,
} from './FileMeta';

/**
 * 
 * @export
 * @interface ApiV1ChatsChatIdFilesPut200Response
 */
export interface ApiV1ChatsChatIdFilesPut200Response {
    /**
     * 
     * @type {FileMeta}
     * @memberof ApiV1ChatsChatIdFilesPut200Response
     */
    data?: FileMeta;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatsChatIdFilesPut200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the ApiV1ChatsChatIdFilesPut200Response interface.
 */
export function instanceOfApiV1ChatsChatIdFilesPut200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1ChatsChatIdFilesPut200ResponseFromJSON(json: any): ApiV1ChatsChatIdFilesPut200Response {
    return ApiV1ChatsChatIdFilesPut200ResponseFromJSONTyped(json, false);
}

export function ApiV1ChatsChatIdFilesPut200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatsChatIdFilesPut200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : FileMetaFromJSON(json['data']),
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ApiV1ChatsChatIdFilesPut200ResponseToJSON(value?: ApiV1ChatsChatIdFilesPut200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': FileMetaToJSON(value.data),
        'status': value.status,
    };
}

