/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MessageMessage } from './MessageMessage';
import {
    MessageMessageFromJSON,
    MessageMessageFromJSONTyped,
    MessageMessageToJSON,
} from './MessageMessage';

/**
 * 
 * @export
 * @interface ApiV1SubscribeGet200ResponseEventsInnerAllOfData
 */
export interface ApiV1SubscribeGet200ResponseEventsInnerAllOfData {
    /**
     * 
     * @type {MessageMessage}
     * @memberof ApiV1SubscribeGet200ResponseEventsInnerAllOfData
     */
    message?: MessageMessage;
}

/**
 * Check if a given object implements the ApiV1SubscribeGet200ResponseEventsInnerAllOfData interface.
 */
export function instanceOfApiV1SubscribeGet200ResponseEventsInnerAllOfData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1SubscribeGet200ResponseEventsInnerAllOfDataFromJSON(json: any): ApiV1SubscribeGet200ResponseEventsInnerAllOfData {
    return ApiV1SubscribeGet200ResponseEventsInnerAllOfDataFromJSONTyped(json, false);
}

export function ApiV1SubscribeGet200ResponseEventsInnerAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SubscribeGet200ResponseEventsInnerAllOfData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : MessageMessageFromJSON(json['message']),
    };
}

export function ApiV1SubscribeGet200ResponseEventsInnerAllOfDataToJSON(value?: ApiV1SubscribeGet200ResponseEventsInnerAllOfData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': MessageMessageToJSON(value.message),
    };
}

