/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ChatsPostRequest
 */
export interface ApiV1ChatsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatsPostRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the ApiV1ChatsPostRequest interface.
 */
export function instanceOfApiV1ChatsPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1ChatsPostRequestFromJSON(json: any): ApiV1ChatsPostRequest {
    return ApiV1ChatsPostRequestFromJSONTyped(json, false);
}

export function ApiV1ChatsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatsPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function ApiV1ChatsPostRequestToJSON(value?: ApiV1ChatsPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

