/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiV1LoginPost200ResponseData } from './ApiV1LoginPost200ResponseData';
import {
    ApiV1LoginPost200ResponseDataFromJSON,
    ApiV1LoginPost200ResponseDataFromJSONTyped,
    ApiV1LoginPost200ResponseDataToJSON,
} from './ApiV1LoginPost200ResponseData';

/**
 * 
 * @export
 * @interface ApiV1LoginPost200Response
 */
export interface ApiV1LoginPost200Response {
    /**
     * 
     * @type {ApiV1LoginPost200ResponseData}
     * @memberof ApiV1LoginPost200Response
     */
    data?: ApiV1LoginPost200ResponseData;
    /**
     * 
     * @type {object}
     * @memberof ApiV1LoginPost200Response
     */
    fiberMap?: object;
    /**
     * 
     * @type {string}
     * @memberof ApiV1LoginPost200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the ApiV1LoginPost200Response interface.
 */
export function instanceOfApiV1LoginPost200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1LoginPost200ResponseFromJSON(json: any): ApiV1LoginPost200Response {
    return ApiV1LoginPost200ResponseFromJSONTyped(json, false);
}

export function ApiV1LoginPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1LoginPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ApiV1LoginPost200ResponseDataFromJSON(json['data']),
        'fiberMap': !exists(json, 'fiber.Map') ? undefined : json['fiber.Map'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ApiV1LoginPost200ResponseToJSON(value?: ApiV1LoginPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ApiV1LoginPost200ResponseDataToJSON(value.data),
        'fiber.Map': value.fiberMap,
        'status': value.status,
    };
}

