/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MessageMessage } from './MessageMessage';
import {
    MessageMessageFromJSON,
    MessageMessageFromJSONTyped,
    MessageMessageToJSON,
} from './MessageMessage';

/**
 * 
 * @export
 * @interface ApiV1ChatsChatIdMessagesGet200Response
 */
export interface ApiV1ChatsChatIdMessagesGet200Response {
    /**
     * 
     * @type {Array<MessageMessage>}
     * @memberof ApiV1ChatsChatIdMessagesGet200Response
     */
    data?: Array<MessageMessage>;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatsChatIdMessagesGet200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the ApiV1ChatsChatIdMessagesGet200Response interface.
 */
export function instanceOfApiV1ChatsChatIdMessagesGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1ChatsChatIdMessagesGet200ResponseFromJSON(json: any): ApiV1ChatsChatIdMessagesGet200Response {
    return ApiV1ChatsChatIdMessagesGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1ChatsChatIdMessagesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatsChatIdMessagesGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(MessageMessageFromJSON)),
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ApiV1ChatsChatIdMessagesGet200ResponseToJSON(value?: ApiV1ChatsChatIdMessagesGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(MessageMessageToJSON)),
        'status': value.status,
    };
}

