/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1OtsPostRequest
 */
export interface ApiV1OtsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1OtsPostRequest
     */
    data?: string;
}

/**
 * Check if a given object implements the ApiV1OtsPostRequest interface.
 */
export function instanceOfApiV1OtsPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1OtsPostRequestFromJSON(json: any): ApiV1OtsPostRequest {
    return ApiV1OtsPostRequestFromJSONTyped(json, false);
}

export function ApiV1OtsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1OtsPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function ApiV1OtsPostRequestToJSON(value?: ApiV1OtsPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
    };
}

