/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1RegisterPostRequestAllOf
 */
export interface ApiV1RegisterPostRequestAllOf {
    /**
     * 
     * @type {string}
     * @memberof ApiV1RegisterPostRequestAllOf
     */
    login?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1RegisterPostRequestAllOf
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1RegisterPostRequestAllOf
     */
    password?: string;
}

/**
 * Check if a given object implements the ApiV1RegisterPostRequestAllOf interface.
 */
export function instanceOfApiV1RegisterPostRequestAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1RegisterPostRequestAllOfFromJSON(json: any): ApiV1RegisterPostRequestAllOf {
    return ApiV1RegisterPostRequestAllOfFromJSONTyped(json, false);
}

export function ApiV1RegisterPostRequestAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RegisterPostRequestAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'login': !exists(json, 'login') ? undefined : json['login'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function ApiV1RegisterPostRequestAllOfToJSON(value?: ApiV1RegisterPostRequestAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'login': value.login,
        'name': value.name,
        'password': value.password,
    };
}

