/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1LoginPostRequestAllOf
 */
export interface ApiV1LoginPostRequestAllOf {
    /**
     * 
     * @type {string}
     * @memberof ApiV1LoginPostRequestAllOf
     */
    login?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1LoginPostRequestAllOf
     */
    password?: string;
}

/**
 * Check if a given object implements the ApiV1LoginPostRequestAllOf interface.
 */
export function instanceOfApiV1LoginPostRequestAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1LoginPostRequestAllOfFromJSON(json: any): ApiV1LoginPostRequestAllOf {
    return ApiV1LoginPostRequestAllOfFromJSONTyped(json, false);
}

export function ApiV1LoginPostRequestAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1LoginPostRequestAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'login': !exists(json, 'login') ? undefined : json['login'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function ApiV1LoginPostRequestAllOfToJSON(value?: ApiV1LoginPostRequestAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'login': value.login,
        'password': value.password,
    };
}

