/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1PushWebServerPublicKeyGet200Response
 */
export interface ApiV1PushWebServerPublicKeyGet200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV1PushWebServerPublicKeyGet200Response
     */
    data?: string;
    /**
     * 
     * @type {object}
     * @memberof ApiV1PushWebServerPublicKeyGet200Response
     */
    fiberMap?: object;
    /**
     * 
     * @type {string}
     * @memberof ApiV1PushWebServerPublicKeyGet200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the ApiV1PushWebServerPublicKeyGet200Response interface.
 */
export function instanceOfApiV1PushWebServerPublicKeyGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1PushWebServerPublicKeyGet200ResponseFromJSON(json: any): ApiV1PushWebServerPublicKeyGet200Response {
    return ApiV1PushWebServerPublicKeyGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1PushWebServerPublicKeyGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1PushWebServerPublicKeyGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
        'fiberMap': !exists(json, 'fiber.Map') ? undefined : json['fiber.Map'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ApiV1PushWebServerPublicKeyGet200ResponseToJSON(value?: ApiV1PushWebServerPublicKeyGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'fiber.Map': value.fiberMap,
        'status': value.status,
    };
}

