/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChatChat } from './ChatChat';
import {
    ChatChatFromJSON,
    ChatChatFromJSONTyped,
    ChatChatToJSON,
} from './ChatChat';

/**
 * 
 * @export
 * @interface ApiV1ChatsPost200Response
 */
export interface ApiV1ChatsPost200Response {
    /**
     * 
     * @type {ChatChat}
     * @memberof ApiV1ChatsPost200Response
     */
    data?: ChatChat;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatsPost200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the ApiV1ChatsPost200Response interface.
 */
export function instanceOfApiV1ChatsPost200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1ChatsPost200ResponseFromJSON(json: any): ApiV1ChatsPost200Response {
    return ApiV1ChatsPost200ResponseFromJSONTyped(json, false);
}

export function ApiV1ChatsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatsPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ChatChatFromJSON(json['data']),
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ApiV1ChatsPost200ResponseToJSON(value?: ApiV1ChatsPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ChatChatToJSON(value.data),
        'status': value.status,
    };
}

