/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1OtsPost200ResponseAllOfData
 */
export interface ApiV1OtsPost200ResponseAllOfData {
    /**
     * 
     * @type {string}
     * @memberof ApiV1OtsPost200ResponseAllOfData
     */
    code?: string;
}

/**
 * Check if a given object implements the ApiV1OtsPost200ResponseAllOfData interface.
 */
export function instanceOfApiV1OtsPost200ResponseAllOfData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1OtsPost200ResponseAllOfDataFromJSON(json: any): ApiV1OtsPost200ResponseAllOfData {
    return ApiV1OtsPost200ResponseAllOfDataFromJSONTyped(json, false);
}

export function ApiV1OtsPost200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1OtsPost200ResponseAllOfData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
    };
}

export function ApiV1OtsPost200ResponseAllOfDataToJSON(value?: ApiV1OtsPost200ResponseAllOfData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
    };
}

