/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthPushSubscription } from './AuthPushSubscription';
import {
    AuthPushSubscriptionFromJSON,
    AuthPushSubscriptionFromJSONTyped,
    AuthPushSubscriptionToJSON,
} from './AuthPushSubscription';

/**
 * 
 * @export
 * @interface ApiV1PushWebGet200Response
 */
export interface ApiV1PushWebGet200Response {
    /**
     * 
     * @type {Array<AuthPushSubscription>}
     * @memberof ApiV1PushWebGet200Response
     */
    data?: Array<AuthPushSubscription>;
    /**
     * 
     * @type {string}
     * @memberof ApiV1PushWebGet200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the ApiV1PushWebGet200Response interface.
 */
export function instanceOfApiV1PushWebGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1PushWebGet200ResponseFromJSON(json: any): ApiV1PushWebGet200Response {
    return ApiV1PushWebGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1PushWebGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1PushWebGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(AuthPushSubscriptionFromJSON)),
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ApiV1PushWebGet200ResponseToJSON(value?: ApiV1PushWebGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(AuthPushSubscriptionToJSON)),
        'status': value.status,
    };
}

