/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ChatsChatIdInvitePost200Response
 */
export interface ApiV1ChatsChatIdInvitePost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatsChatIdInvitePost200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the ApiV1ChatsChatIdInvitePost200Response interface.
 */
export function instanceOfApiV1ChatsChatIdInvitePost200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1ChatsChatIdInvitePost200ResponseFromJSON(json: any): ApiV1ChatsChatIdInvitePost200Response {
    return ApiV1ChatsChatIdInvitePost200ResponseFromJSONTyped(json, false);
}

export function ApiV1ChatsChatIdInvitePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatsChatIdInvitePost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ApiV1ChatsChatIdInvitePost200ResponseToJSON(value?: ApiV1ChatsChatIdInvitePost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}

