/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiV1LoginPost200ResponseAllOfData } from './ApiV1LoginPost200ResponseAllOfData';
import {
    ApiV1LoginPost200ResponseAllOfDataFromJSON,
    ApiV1LoginPost200ResponseAllOfDataFromJSONTyped,
    ApiV1LoginPost200ResponseAllOfDataToJSON,
} from './ApiV1LoginPost200ResponseAllOfData';

/**
 * 
 * @export
 * @interface ApiV1LoginPost200Response
 */
export interface ApiV1LoginPost200Response {
    /**
     * 
     * @type {ApiV1LoginPost200ResponseAllOfData}
     * @memberof ApiV1LoginPost200Response
     */
    data?: ApiV1LoginPost200ResponseAllOfData;
    /**
     * 
     * @type {string}
     * @memberof ApiV1LoginPost200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the ApiV1LoginPost200Response interface.
 */
export function instanceOfApiV1LoginPost200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1LoginPost200ResponseFromJSON(json: any): ApiV1LoginPost200Response {
    return ApiV1LoginPost200ResponseFromJSONTyped(json, false);
}

export function ApiV1LoginPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1LoginPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ApiV1LoginPost200ResponseAllOfDataFromJSON(json['data']),
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ApiV1LoginPost200ResponseToJSON(value?: ApiV1LoginPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ApiV1LoginPost200ResponseAllOfDataToJSON(value.data),
        'status': value.status,
    };
}

