/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiV1SubscribeGet200ResponseEventsInnerAllOfData } from './ApiV1SubscribeGet200ResponseEventsInnerAllOfData';
import {
    ApiV1SubscribeGet200ResponseEventsInnerAllOfDataFromJSON,
    ApiV1SubscribeGet200ResponseEventsInnerAllOfDataFromJSONTyped,
    ApiV1SubscribeGet200ResponseEventsInnerAllOfDataToJSON,
} from './ApiV1SubscribeGet200ResponseEventsInnerAllOfData';

/**
 * 
 * @export
 * @interface ApiV1SubscribeGet200ResponseEventsInnerAllOf
 */
export interface ApiV1SubscribeGet200ResponseEventsInnerAllOf {
    /**
     * 
     * @type {string}
     * @memberof ApiV1SubscribeGet200ResponseEventsInnerAllOf
     */
    category?: string;
    /**
     * 
     * @type {ApiV1SubscribeGet200ResponseEventsInnerAllOfData}
     * @memberof ApiV1SubscribeGet200ResponseEventsInnerAllOf
     */
    data?: ApiV1SubscribeGet200ResponseEventsInnerAllOfData;
    /**
     * 
     * @type {number}
     * @memberof ApiV1SubscribeGet200ResponseEventsInnerAllOf
     */
    timestamp?: number;
}

/**
 * Check if a given object implements the ApiV1SubscribeGet200ResponseEventsInnerAllOf interface.
 */
export function instanceOfApiV1SubscribeGet200ResponseEventsInnerAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1SubscribeGet200ResponseEventsInnerAllOfFromJSON(json: any): ApiV1SubscribeGet200ResponseEventsInnerAllOf {
    return ApiV1SubscribeGet200ResponseEventsInnerAllOfFromJSONTyped(json, false);
}

export function ApiV1SubscribeGet200ResponseEventsInnerAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SubscribeGet200ResponseEventsInnerAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'category': !exists(json, 'category') ? undefined : json['category'],
        'data': !exists(json, 'data') ? undefined : ApiV1SubscribeGet200ResponseEventsInnerAllOfDataFromJSON(json['data']),
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
    };
}

export function ApiV1SubscribeGet200ResponseEventsInnerAllOfToJSON(value?: ApiV1SubscribeGet200ResponseEventsInnerAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'category': value.category,
        'data': ApiV1SubscribeGet200ResponseEventsInnerAllOfDataToJSON(value.data),
        'timestamp': value.timestamp,
    };
}

