/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ChatsChatIdInvitePostRequest
 */
export interface ApiV1ChatsChatIdInvitePostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatsChatIdInvitePostRequest
     */
    login?: string;
}

/**
 * Check if a given object implements the ApiV1ChatsChatIdInvitePostRequest interface.
 */
export function instanceOfApiV1ChatsChatIdInvitePostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiV1ChatsChatIdInvitePostRequestFromJSON(json: any): ApiV1ChatsChatIdInvitePostRequest {
    return ApiV1ChatsChatIdInvitePostRequestFromJSONTyped(json, false);
}

export function ApiV1ChatsChatIdInvitePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatsChatIdInvitePostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'login': !exists(json, 'login') ? undefined : json['login'],
    };
}

export function ApiV1ChatsChatIdInvitePostRequestToJSON(value?: ApiV1ChatsChatIdInvitePostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'login': value.login,
    };
}

