/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AuthPushSubscriptionType = {
    Web: 'web'
} as const;
export type AuthPushSubscriptionType = typeof AuthPushSubscriptionType[keyof typeof AuthPushSubscriptionType];


export function AuthPushSubscriptionTypeFromJSON(json: any): AuthPushSubscriptionType {
    return AuthPushSubscriptionTypeFromJSONTyped(json, false);
}

export function AuthPushSubscriptionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthPushSubscriptionType {
    return json as AuthPushSubscriptionType;
}

export function AuthPushSubscriptionTypeToJSON(value?: AuthPushSubscriptionType | null): any {
    return value as any;
}

