/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FileAccessor = {
    Public: 'public',
    Private: 'private'
} as const;
export type FileAccessor = typeof FileAccessor[keyof typeof FileAccessor];


export function FileAccessorFromJSON(json: any): FileAccessor {
    return FileAccessorFromJSONTyped(json, false);
}

export function FileAccessorFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileAccessor {
    return json as FileAccessor;
}

export function FileAccessorToJSON(value?: FileAccessor | null): any {
    return value as any;
}

