/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Get200ResponseData } from './Get200ResponseData';
import {
    Get200ResponseDataFromJSON,
    Get200ResponseDataFromJSONTyped,
    Get200ResponseDataToJSON,
} from './Get200ResponseData';

/**
 * 
 * @export
 * @interface Get200Response
 */
export interface Get200Response {
    /**
     * 
     * @type {Get200ResponseData}
     * @memberof Get200Response
     */
    data?: Get200ResponseData;
    /**
     * 
     * @type {object}
     * @memberof Get200Response
     */
    fiberMap?: object;
    /**
     * 
     * @type {string}
     * @memberof Get200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the Get200Response interface.
 */
export function instanceOfGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Get200ResponseFromJSON(json: any): Get200Response {
    return Get200ResponseFromJSONTyped(json, false);
}

export function Get200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Get200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : Get200ResponseDataFromJSON(json['data']),
        'fiberMap': !exists(json, 'fiber.Map') ? undefined : json['fiber.Map'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function Get200ResponseToJSON(value?: Get200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': Get200ResponseDataToJSON(value.data),
        'fiber.Map': value.fiberMap,
        'status': value.status,
    };
}

