/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Get200ResponseData
 */
export interface Get200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof Get200ResponseData
     */
    message?: string;
}

/**
 * Check if a given object implements the Get200ResponseData interface.
 */
export function instanceOfGet200ResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Get200ResponseDataFromJSON(json: any): Get200ResponseData {
    return Get200ResponseDataFromJSONTyped(json, false);
}

export function Get200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Get200ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function Get200ResponseDataToJSON(value?: Get200ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

