/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Get200ResponseAllOfData
 */
export interface Get200ResponseAllOfData {
    /**
     * 
     * @type {string}
     * @memberof Get200ResponseAllOfData
     */
    message?: string;
}

/**
 * Check if a given object implements the Get200ResponseAllOfData interface.
 */
export function instanceOfGet200ResponseAllOfData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Get200ResponseAllOfDataFromJSON(json: any): Get200ResponseAllOfData {
    return Get200ResponseAllOfDataFromJSONTyped(json, false);
}

export function Get200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Get200ResponseAllOfData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function Get200ResponseAllOfDataToJSON(value?: Get200ResponseAllOfData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

