/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VersionGet200ResponseData
 */
export interface VersionGet200ResponseData {
    /**
     * 
     * @type {number}
     * @memberof VersionGet200ResponseData
     */
    build?: number;
    /**
     * 
     * @type {string}
     * @memberof VersionGet200ResponseData
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof VersionGet200ResponseData
     */
    version?: string;
}

/**
 * Check if a given object implements the VersionGet200ResponseData interface.
 */
export function instanceOfVersionGet200ResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VersionGet200ResponseDataFromJSON(json: any): VersionGet200ResponseData {
    return VersionGet200ResponseDataFromJSONTyped(json, false);
}

export function VersionGet200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionGet200ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'build': !exists(json, 'build') ? undefined : json['build'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function VersionGet200ResponseDataToJSON(value?: VersionGet200ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'build': value.build,
        'subject': value.subject,
        'version': value.version,
    };
}

