/* tslint:disable */
/* eslint-disable */
/**
 * Khalad API
 * This is open source Khala server implementation.
 *
 * The version of the OpenAPI document: 0.1.0-alpha.1
 * Contact: info@cnodax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VersionGet200ResponseData } from './VersionGet200ResponseData';
import {
    VersionGet200ResponseDataFromJSON,
    VersionGet200ResponseDataFromJSONTyped,
    VersionGet200ResponseDataToJSON,
} from './VersionGet200ResponseData';

/**
 * 
 * @export
 * @interface VersionGet200Response
 */
export interface VersionGet200Response {
    /**
     * 
     * @type {VersionGet200ResponseData}
     * @memberof VersionGet200Response
     */
    data?: VersionGet200ResponseData;
    /**
     * 
     * @type {object}
     * @memberof VersionGet200Response
     */
    fiberMap?: object;
    /**
     * 
     * @type {string}
     * @memberof VersionGet200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the VersionGet200Response interface.
 */
export function instanceOfVersionGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VersionGet200ResponseFromJSON(json: any): VersionGet200Response {
    return VersionGet200ResponseFromJSONTyped(json, false);
}

export function VersionGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : VersionGet200ResponseDataFromJSON(json['data']),
        'fiberMap': !exists(json, 'fiber.Map') ? undefined : json['fiber.Map'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function VersionGet200ResponseToJSON(value?: VersionGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': VersionGet200ResponseDataToJSON(value.data),
        'fiber.Map': value.fiberMap,
        'status': value.status,
    };
}

